### ISSUE TITLE
[BUG] MSAL Failure 

### ISSUE THREAD

**Issue by das-anubhav** [Azure/azure-sdk-for-ios#1005]
**Description of the bug**
Whenever the user selects an image after pressing the upload button this message appears.

**Screenshot**
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-27 at 21 20 32](https://user-images.githubusercontent.com/56907051/131155190-ba9552bb-8e23-473e-8abb-3ea4fb5c0988.png)

**Comment by tjprescott** [comment]
Hi @das-anubhav. `AzureStorageBlob` and `AzureIdentity` are works in progress, and not yet even in preview status. As such, we are not providing support for them at this time.
