### ISSUE TITLE
[BUG] EXC_BAD_INSTRUCTION 

### ISSUE THREAD

**Issue by das-anubhav** [Azure/azure-sdk-for-ios#1006]
**Describe the bug**
Whenever the user press the button Media or selects an image from the upload, the app crashes.

***Code Snippet***
defer { group.leave() }

**Comment by tjprescott** [comment]
Hi @das-anubhav. `AzureStorageBlob` and `AzureIdentity` are works in progress, and not yet even in preview status. As such, we are not providing support for them at this time.
