### ISSUE TITLE
File upload on my azure sever

### ISSUE THREAD

**Issue by ErAshu** [Azure/azure-sdk-for-ios#1118]
I want to upload File on my azure sever. Which SDK i have to use? I have my azure subscription. I am using Swift 5.

**Comment by tjprescott** [comment]
Hi @ErAshu you would use some variant of the Azure Storage library, but the storage code that is in this repo is just experimental at this point. There is an Objective-C-based storage library that is officially supported here:
https://github.com/Azure/azure-storage-ios

It should bridge to Swift. I hope that helps, and sorry for the delay in response.
