### ISSUE TITLE
Update SwiftPM mirror repos so the code reflects the latest code

### ISSUE THREAD

**Issue by angellan-msft** [Azure/azure-sdk-for-ios#1124]
**Describe the bug**
For SwiftPM-AzureCommunicationChat mirror repository, releases are tagged but the repo itself has not been updated, this can be misleading and confusing for people who visit that page. We need to update the actual repository with the latest release.

***Exception or Stack Trace***
N/A

**To Reproduce**
N/A

***Code Snippet***
N/A

**Expected behavior**
We expected the code of SPM mirror repository master branch to be updated to our latest release.

**Screenshots**
![image](https://user-images.githubusercontent.com/95160885/149241570-849c0fb0-cede-4cdb-80ba-c1b0533db38b.png)
From the above image we can see all codes are in "1.0.0-beta.12". 

![image](https://user-images.githubusercontent.com/95160885/149241946-ffd13ed1-2560-49e4-8db9-34e255439fd6.png)
The tags show that the latest release is "1.1.0-beta.2", which is newer than the repo itself.

**Setup (please complete the following information):**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by tjprescott** [comment]
This is true of _all_ the mirror repos and the change should apply uniformly.

**Comment by benbp** [comment]
After talking with @tjprescott, I think the best resolution to this is for us to replace all code in the master branch with a small README that explains the mirror repo and redirects people to [azure-sdk-for-ios](https://github.com/Azure/azure-sdk-for-ios/) repository for things like issues and pull requests.

We'll need some sort of common readme, perhaps in the main repo, and a sync process for updating the mirror repositories or adding new ones.

@weshaggard thoughts?

**Comment by weshaggard** [comment]
I'm fine with that as an approach. Let's make sure the partners are good with that.

**Comment by angellan-msft** [comment]
I’m fine with it as well. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by benbp** [comment]
@angellan-msft this should update for the communication repos on the next release/sync to them, but let us know if you'd like us to manually update sooner.
