### ISSUE TITLE
[BUG] AzureCore swallows errors instead of raising them

### ISSUE THREAD

**Issue by angellan-msft** [Azure/azure-sdk-for-ios#1139]
**Describe the bug**
One of our clients is using ACS Swift sdk for messaging feature.
Link to the github -  https://github.com/Azure/SwiftPM-AzureCommunicationChat.git,
version: "1.0.2
 
They are trying to handle error cases that arises because of absence of network (Internet not available).
 
For example: User typed a text and hit “send” at the time when he was out of network.
 
Here they expect SDK to return the callback with error so that they can take retry action based on that.
But SDK is not sending any callbacks for any request that is sent when network is not available.

***Exception or Stack Trace***
N/A

**To Reproduce**
1) connect the Iphone to local MacBook and keep the wifi on
2) set several breakpoints and run the program
3) when the program stops at the point where the user sends the message, turn off the iphone's wifi
4) keep running the program and it will stop at the most bottom layer, showing an error captured by datatask API of URLSession
5) keep running the program and it will exit directly (instead of throwing the error back to the upper layer which is Azure Core Pipeline)

***Code Snippet***
When below code is executed in absence of network (with valid chatThreadClient object pertaining to a valid thread)
It should return the callback with corresponding httpError or result with failure case.  But this callback doesn’t get called.
 ```
chatThreadClient.send(message: message) { result, httpError in
                   switch result {
                    case let .success(result):
                        promise(.success(result.id))
                    case .failure:
                        promise(Result.failure(AcsMessagingError.sendMessageError.toStandardError()))
                    }
                }
```
The AzureCore PipelineClient calls the below function. The error will be captured in the below codes but will not be returned to AzureCore PipelineClient through the callback.
```
session.dataTask(with: urlRequest) { data, response, error in
            ...
            if let error = error {
                completionHandler(.failure(AzureError.service("Service error.", error)), httpResponse)
            } else {
                ...
            }
}.resume()
```

**Expected behavior**
When "chatThreadClient.send(message: message) " is executed in absence of network. It should return the callback with corresponding httpError or result with failure case.  

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: iOS
 - IDE : Xcode
 - version: "AzureCore", url: "https://github.com/Azure/SwiftPM-AzureCore.git", .exact("1.0.0-beta.13")

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by tjprescott** [comment]
Part of the problem here is that the `on(error:_)` implementation for `ContentEncodeDecodePolicy` has a bug where it had code paths that broke the completion handler chain. A fix for AzureCore is upcoming.
