### ISSUE TITLE
[FEATURE REQ] Calling SDK - iOS - Raw media access - outgoing video

### ISSUE THREAD

**Issue by antpass79** [Azure/azure-sdk-for-ios#1141]
I can send raw frames through ACS to Teams meeting with Android sdk (https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access).
I saw in the roadmap that the version for Windows UWP is in private preview.
Is there a plan to do the same thing with iOS?

**Comment by tjprescott** [comment]
@mariusu-msft for comment. Feel free to transfer to your Calling repo if you prefer.

**Comment by tjprescott** [comment]
Issue moved to [Azure/Communication #439](https://github.com/Azure/Communication/issues/439) via [**ZenHub**](https://www.zenhub.com/)
