### ISSUE TITLE
[BUG] Audio doesn't work after ongoing was meeting was interrupted through a phone call

### ISSUE THREAD

**Issue by mkambale** [Azure/azure-sdk-for-ios#1146]
**Describe the bug**
If user receives phone call during meeting, user keeps teams call on hold and receives phone call, after the phone call ends and user resumes the call, input and output audio doesn't work.

**To Reproduce**
1. User joins a scheduled meeting using url and token as a guest using his iPhone through my app XYZ.
2. Host joins using Teams app on his/her desktop.
3. Host admits guest.
4. User receives a phone call.
5. User keeps meeting on hold on app.
6. User accepts phone call and answers.
7. User ends phone call.
8. User returns to app XYZ and resumes Teams meeting call.
9. User cannot hear anything, host cannot hear user.

**Setup (please complete the following information):**
 - OS: [e.g. iOS] iOS 15.2
 - IDE : [e.g. IntelliJ]
 - Version of the Library used:    AzureCommunicationCalling - 2.0.0
                                                      AzureCommunicationCommon - 1.0.2

**Additional context**
didChangeSpeakingState() call back is received after the when host speaks, but user cannot hear anything.

Any suggestions appreceited.

Thanks,

**Comment by tjprescott** [comment]
@mariusu-msft for triage.
