### ISSUE TITLE
"AzureCommunicationChat" library giving issue randomly while sending and listing messages.

### ISSUE THREAD

**Issue by Kamaljeetsinghpunia** [Azure/azure-sdk-for-ios#1187]
This is the error which I am getting while sending or listing the messages.

client("Decoding error.", Optional(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "error", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"error\", intValue: nil) (\"error\").", underlyingError: nil))))

Some time it works when sending and listing the messages but some time it displays the above error message. Please let me know what to do with this?

Thank you
Kamaljeet Singh

**Comment by tjprescott** [comment]
@angellan-msft @LuChen-Microsoft can you please take a look.

**Comment by angellan-msft** [comment]
> This is the error which I am getting while sending or listing the messages.
> 
> client("Decoding error.", Optional(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "error", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: "error", intValue: nil) ("error").", underlyingError: nil))))
> 
> Some time it works when sending and listing the messages but some time it displays the above error message. Please let me know what to do with this?
> 
> Thank you Kamaljeet Singh

Hi Kamaljeetsinghpunia, thanks for your question. I took a look at this issue. This should be an error thrown out when the returned data is deserialized. Could you please let us know under which context you receive this error? And what are the requests look like? Could you share the code on your side if possible? Thanks!

**Comment by Kamaljeetsinghpunia** [comment]
Hi, 

Here is the code which I am using for sending message.

```
private func sendMessage() {
        self.isSendMessageInProgress = true
        let message = SendChatMessageRequest(
            content: self.chatMessage.trimmingCharacters(in: .whitespacesAndNewlines),
            senderDisplayName: self.displayName,
            type: .text
        )
        print("sending message: \(message)")
        
        self.chatThreadClient?.send(message: message) { result, _ in
            switch result {
            case .success:
                print("Chat message sent")
            case .failure(let error):
                print("Failed to send chat message: \(error)")
            }
            
            self.chatMessage = ""
            self.isSendMessageInProgress = false
        }
    }
```

And this is the error returned by above function.

`Failed to send chat message: client("Decoding error.", Optional(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "error", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"error\", intValue: nil) (\"error\").", underlyingError: nil))))`

**Comment by Kamaljeetsinghpunia** [comment]
Hi, 

I have found the issue. Which threadID I was using for creating ChatThreadClient it was URL encoded string. But I don't know why it was working sometimes and sometimes don't. But now sending message is working fine for me after removing the URL encoding.

Thanks.
