### ISSUE TITLE
Using AzureCommunicationChat (1.0.1) I am unable to upload iOS build on AppStore.

### ISSUE THREAD

**Issue by Kamaljeetsinghpunia** [Azure/azure-sdk-for-ios#1203]
I am using AzureCommunicationChat (1.0.1) and AzureCommunicationChat is using Trouter (0.0.1-beta.5) which is now allowing me to upload the app on AppStore.

***Exception or Stack Trace***
App Store Connect Operation Error
Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'iOSVideo.app/Frameworks/Trouter.framework' is ''.

App Store Connect Operation Error
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle iOSVideo.app/Frameworks/Trouter.framework is required.

App Store Connect Operation Error
The bundle 'Payload/iOSVideo.app/Frameworks/Trouter.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

App Store Connect Operation Error
This bundle Payload/iOSVideo.app/Frameworks/Trouter.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

App Store Connect Operation Error
Invalid Bundle. The bundle iOSVideo.app/Frameworks/Trouter.framework does not support the minimum OS Version specified in the Info.plist.

**Screenshots**
![Screenshot 2022-03-10 at 11 48 19 AM](https://user-images.githubusercontent.com/95396105/157601143-8308e835-f11f-4797-860a-e7a01569e7dc.png)

**Setup (please complete the following information):**
Libraries version numbers.
AzureCommunicationChat (1.0.1)
Trouter (0.0.1-beta.5)

**Additional context**
If I don't set "Enable bitcode" to "YES" for AzureCommunicationChat && Trouter then project don't get build but if I set "Enable bitcode" to "NO" then it gives the above mentioned error.

Please let me know what I can do with this issue.

Thank you 
Kamaljeet Singh

**Comment by tjprescott** [comment]
@angellan-msft @LuChen-Microsoft for comment. cc/ @juancamilor

**Comment by Kamaljeetsinghpunia** [comment]
Any update on this?

**Comment by tjprescott** [comment]
@Kamaljeetsinghpunia I apologize for the delay. @angellan-msft @LuChen-Microsoft @juancamilor are representatives from the service team and should be able to assist.

**Comment by angellan-msft** [comment]
Hi @Kamaljeetsinghpunia , this is a known issue in version 1.0.1, please try with a later version (1.0.2 or above). Thanks!

**Comment by Kamaljeetsinghpunia** [comment]
Ok Thank you
