### ISSUE TITLE
[BUG] Wrong value`isMuted` from particiapant muted by remote

### ISSUE THREAD

**Issue by dudeck** [Azure/azure-sdk-for-ios#1251]
**Describe the bug**
When meeting owner in Dekstop app mutes participant on a meeting, ACS SDK sends`isMuted` value as `false` instead of `true`.

**To Reproduce**
Have a Teams meeting with Owner.
Admit User who uses app with azure-sdk-for-ios.
Mute User in Desktop app.
Read emmited value `isMuted` from `ACSCall` object.

**Sample code**
```
import AzureCommunicationCalling

    func call(_ call: Call, didChangeMuteState args: PropertyChangedEventArgs) {
        print("Muted: \(call.isMuted)")
    }
```

**Expected behavior**
`isMuted` should return `true`.

**Screenshots**
<img width="117" alt="obraz" src="https://user-images.githubusercontent.com/22682687/165947187-945440b8-4615-4455-ada8-1cbc4b0454bc.png">

**Setup (please complete the following information):**
 - OS: iOS 14.7.1 iPhone 6s Plus
 - IDE : XCode
 - Version of the Library used: AzureCommunicationCalling (2.0.0)
 ***
 PODS:
  - AzureCommunicationCalling (2.0.0):
    - AzureCommunicationCommon (~> 1.0.2)
  - AzureCommunicationCommon (1.0.3)
  ***

**Comment by tjprescott** [comment]
@dudeck thank you for reporting this. @raosanat can you please transfer this issue to your repo for action?

**Comment by dudeck** [comment]
Thank you very much! It works on version 2.2.0! Closing this issue.
