### ISSUE TITLE
Installation issues using instructions and Demo application

### ISSUE THREAD

**Issue by elemental21** [Azure/azure-sdk-for-ios#1299]
Using the instructions found here:
https://github.com/Azure/azure-sdk-for-ios/tree/main/sdk/core/AzureCore#add-a-package-dependency-with-swift-package-manager

Tried: **Add a package dependency with Swift Package Manager via XCode**:
Error I get with that method:
![image](https://user-images.githubusercontent.com/7585464/176536694-643867eb-33db-4421-9ead-df11a63407f3.png)

Tried: **Swift CLI**
Error: No such module 'PackageDescritpion'

Tried: **Integrate the client libraries with CocoaPods**
With my project when I run "pod install" I get the error:
`Specs satisfying the `AzureCore (= 1.0.0-beta.15)` dependency were found, but they required a higher minimum deployment target.
`
So I downloaded the demo project: https://github.com/Azure/azure-sdk-for-ios/tree/main/examples/AzureSDKDemoSwift
and ran "pod install" and it didn't give me the above error.

However, ultimately I always end up with this error when building (with both my project and the AzureSDKDemoSwift project)
![image](https://user-images.githubusercontent.com/7585464/176538205-a0cf8bd6-92b9-4762-a721-633a2039922b.png)

I also tried adding the frameworks manually and it resulted in the "Framework not found AzureCore" error as well

Any help would be greatly appreciated

**Comment by gavinb80** [comment]
I am getting the same issue, cannot add via Package Manager as seems the Package.swift file is missing

**Comment by tjprescott** [comment]
@elemental21 @gavinb80 when you add a package via Swift PM, you need to use the version-based dependency rules, not a branch or commit. The mirror repos exists only to track tagged releases, so the branch/commit approach will not work.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/5723682/180826488-34d34179-1596-4d81-bcb1-65b9b5bd6cb4.png">

For the SDKs in beta, we recommend pinning to `Exact Version` since there can be breaking changes between beta versions.

Please let me know if that helps resolve your issues.

**Comment by elemental21** [comment]
Thanks, that worked. We actually found that solution a little while back after posting this question.  However after doing that I get this next issue when trying to build and haven't been able to get past it. Any suggestions
![image](https://user-images.githubusercontent.com/7585464/181042397-27f2d64d-3e90-4711-a453-d1e9f75b8023.png)

**Comment by tjprescott** [comment]
You cannot install AzureStorageBlob via SPM. It is not released.
https://github.com/Azure/azure-sdk-for-ios/issues/469

**Comment by tjprescott** [comment]
Closing this issue as the storage code that the demo relied upon has been removed from the `main` branch.
