### ISSUE TITLE
[AzureCommunicationCalling] callkit questions

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Azure/azure-sdk-for-ios#1319]
**Describe the bug**

We're having issues implementing the callkit.
When we use createCallAgentWithCallKitOptions the calls work fine with the app open, but with the app dead or in the background, we don't know how to deal with it, because the documentation doesn't leave anything about this implementation of the callkit using createCallAgentWithCallKitOptions, we know that it's about a resource in preview, but I don't see information on how to handle the didReceiveIncomingPush push event for example.

The method createCallAgentWithCallKitOptions should be used for the app in the foreground and in the background do we need to implement the callkit manually as established by apple or is there any method in the version to use it? We also tested callagente.reportToCallKit but we don't know for sure when to use it, if you can clarify with a few lines of code, it would be good, in the documentation I didn't find anything about it.
The only information I could find like anything about it was [here ](https://github.com/Azure/Communication/issues/152)

***Exception or Stack Trace***
---

**To Reproduce**
Use createCallAgentWithCallKitOptions in beta 2.2.0-beta.1

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Calls work in background and with dead app using agent creation with callkit

**Screenshots**

**Setup (please complete the following information):**
 - OS: [iOS 15.5]
 - IDE : [xcode]
 - Version of the Library used 2.2.0-beta.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [ ] Repro Steps Added
- [X] Setup information Added

**Comment by tjprescott** [comment]
@raosanat please take a look.

**Comment by gaobob-msft** [comment]
@xumo-95 can you please take a look. CC @lucianopa-msft

**Comment by xumo-95** [comment]
Hi @andersonvieiragomeslopes ! I'm wondering if you can please confirm the SDK version that you used for your development? CallKitOptions was not released in 2.2.0-beta.1 SDK. Thank you!

**Comment by andersonvieiragomeslopes** [comment]
Hi @xumo-95 .

Well, createCallAgentWithCallKitOptions was released in beta version 1.1.0-beta.1
I'm using version 2.2.0-beta.1 and it has createCallAgentWithCallKitOptions and callagente.reportToCallKit
I need help just to understand how this is supposed to work and work with the dead app, this issue is preventing publishing in production, it's really serious.

Check versions: https://github.com/Azure/azure-sdk-for-ios/blob/main/sdk/communication/AzureCommunicationCalling/CHANGELOG.md#210-beta1-2021-11-12

**Comment by andersonvieiragomeslopes** [comment]
Hello, @tjprescott @raosanat @xumo-95 @gaobob-msft .

With the release of version 2.3.0 for ios the original problem of the ticket is solved, you did a great job adding even more option than the previous one, I noticed two very important items for us: ACSCallKitOptions/configureAudioSession and reportIncomingCallFromKillState, here's a suggestion just that is explain in the documentation, thanks.

**Comment by raosanat** [comment]
@andersonvieiragomeslopes sorry for the late reply we will be updating the documentation soon. Please keep in mind that the feature is still in Beta which is why the documentation isn't up to date yet.

**Comment by andersonvieiragomeslopes** [comment]
@raosanat I understand, thanks for the feature and I will be happy to help with feedback and news about the feature.
