### ISSUE TITLE
DecodingError while getting a collection

### ISSUE THREAD

**Issue by wollodev** [Azure/azure-sdk-for-ios#134]
### Environment

- iOS version: iOS 12.4.1 (16G102)
- Xcode version: Version 10.3 (10G8)
- Azure.iOS SDK: AzureData
- Azure.iOS SDK version: 0.5.0
- CocoaPods or Carthage: CocoaPods

### Bug Summary

Getting a collection for `databaseId` and `collectionId` returns an unknown error, with an baseError, because decoding failed for `IncludedPath`. The attached response doesn't contain any key `indexes`, but the property `indexes` in `DocumentCollection` is mandatory.

### Steps to Reproduce

Get a collection without setting any indexes in cosmos db.
This worked last week for me, today I got this error.

### Code snippet

```swift
AzureData.get(collectionWithId: collectionId, inDatabase: databaseId) { [weak self] response in ... }
```

### Get-Collection-Response

```json
{
    "id": "MyCollection",
    "indexingPolicy": {
        "indexingMode": "consistent",
        "automatic": true,
        "includedPaths": [
            {
                "path": "\/*"
            }
        ],
        "excludedPaths": [
            {
                "path": "\/\"_etag\"\/?"
            }
        ]
    },
    "partitionKey": {
        "paths": [
            "\/ABCDEFG"
        ],
        "kind": "Hash"
    },
    "conflictResolutionPolicy": {
        "mode": "LastWriterWins",
        "conflictResolutionPath": "\/_ts",
        "conflictResolutionProcedure": ""
    },
    "geospatialConfig": {
        "type": "Geography"
    },
    "_rid": "-MxDAWEl4Xk=",
    "_ts": 534534534,
    "_self": "dbs\/-MxNAA==\/colls\/-MxNAIEl4Xk=\/",
    "_etag": "\"0000ad01-0000-0d00-6666-9d6cde230011\"",
    "_docs": "docs\/",
    "_sprocs": "sprocs\/",
    "_triggers": "triggers\/",
    "_udfs": "udfs\/",
    "_conflicts": "conflicts\/"
}
```

### Solution so far
Make `public var indexes: [Index]? ` optional. From my point of view, setting an empty array in the original (`public var indexes: [Index] = []`) doesn't have any effect for `Decodable`.

**Comment by bsiegel** [comment]
Thanks for your report. We are preparing for a release of the Track 2 SDK libraries which are based on a different codebase than the current libraries. Since we're not planning for further releases of the existing libraries, we're not able to work on resolving this issue at the current time.
