### ISSUE TITLE
AzureCore Telemetry (User-Agent) Policy

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#143]
Work necessary to comply with https://azure.github.io/azure-sdk/general_azurecore.html.

- [x] Update User-Agent format according to guidelines
- [x] Explore if possible to find out if client app is primarily Swift or ObjectiveC
- [x] Provide mechanism for client app to set their application ID (name and version) or find way to do this automatically
- [x] ~Provide mechanism for SDK author to specify dynamic telemetry information through "x-ms-azsdk-telemetry" header~
- [ ] Add test coverage

For the user agent, we want to report:

application ID / bundle ID
library name and version
os.version
user.region
user.language
min & target api level / os version
built for debugging
device model & manufacturer
language (swift vs objc)

Determine which of these metrics we can access, then propose an update to the guidelines with the format of the useragent string that we will use to report them. Implement the useragent string to match that guideline.

Also note: The telemetry on-off toggle was not intended to affect the value of the User-Agent header. We don't need to implement any logic inside this policy related to checking the value of that toggle.

**Comment by tjprescott** [comment]
The majority of this can be done quickly. There will be some things that could be difficult and may need to be their own issues (swift vs. objc for example)

**Comment by bsiegel** [comment]
"Provide mechanism for SDK author to specify dynamic telemetry information through "x-ms-azsdk-telemetry" header" - this is a "SHOULD" in the guidelines and I don't see any other language SDKs currently implementing it, going to leave this as a future work item.
