### ISSUE TITLE
Open Source AzureCommunicationCalling

### ISSUE THREAD

**Issue by MaxMilon** [Azure/azure-sdk-for-ios#1478]
Is it planned to make the `AzureCommunicationCalling` package open source in near future? I am asking, because it does not support watchOS, which one could perhaps add by forking the project.

**Comment by tjprescott** [comment]
@raosanat can you please respond to this?

**Comment by raosanat** [comment]
Hi, currently we don't plan to make it open source. But we soon we will add more support like MacOs and WatchOs in the upcoming quarter. Thanks.
