### ISSUE TITLE
[BUG] ARM64 simulator support is missing from the library (calling functionality)

### ISSUE THREAD

**Issue by emlynmac** [Azure/azure-sdk-for-ios#1497]
**Describe the bug**
Support for the Apple Silicon simulator is not included in the library. 
The podfile specifically removes it:
 https://github.com/Azure/azure-sdk-for-ios/blob/main/Podfile#L115

A workaround has been used until Xcode 14.3; run Xcode in rosetta mode. This support has now been removed in Xcode > 14.3

***Exception or Stack Trace***
- NA

**To Reproduce**
Attempt to use an apple silicon mac to build for simulator with the library

***Code Snippet***
Any inclusion of the library on Apple Silicon build

**Expected behaviour**
Build succeeds.

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOS, Xcode 14+ in non-rosetta mode on Apple Silicon
 - IDE : [e.g. IntelliJ]
 - Version of the Library used- any

**Additional context**

**Comment by mh-ereyes** [comment]
Attaching an image with the errors when running with apple silicon. 
The error appears to be with this dependency library:
`        "package": "Trouter",
        "repositoryURL": "https://github.com/microsoft/trouter-client-ios.git"`

![Library error MS](https://user-images.githubusercontent.com/64660842/225779958-c9c73ce8-7cff-4b10-a6d9-a66c2ba740a4.jpg)

**Comment by peterholak** [comment]
This should now be fixed in 0.2.0 https://github.com/CocoaPods/Specs/commit/af20ddff0ab42b86aba98b90d3682b00d77646dd

**Comment by mh-ehedstrom** [comment]
Nice, thank you @peterholak .
We have Trouter pulled in as a dependency of [AzureCommunicationChat](https://github.com/Azure/SwiftPM-AzureCommunicationChat), which has a specific dependency on Trouter 0.1.0.
```
        .package(
            name: "Trouter",
            url: "https://github.com/microsoft/trouter-client-ios.git",
            .exact("0.1.0")
```
from https://github.com/Azure/SwiftPM-AzureCommunicationChat/blob/1.3.0/Package.swift .

Will someone update that library to point to the new Trouter release? Thanks!

**Comment by vhuseinova-msft** [comment]
`Will someone update that library to point to the new Trouter release? `
Hi @mh-ehedstrom! AzureCommunicationChat 1.3.1 is released with an updated Trouter dependency

**Comment by lucianopa-msft** [comment]
> @tjprescott The referenced PR solves the issue for the Chat SDK, but the calling side is still in need of an update.

Calling has added support for arm64 simulator from [2.5.1](https://github.com/Azure/Communication/releases/tag/v2.5.1) forwards.
