### ISSUE TITLE
AzureCore Global Configuration

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#150]
Work necessary to comply with https://azure.github.io/azure-sdk/general_azurecore.html.

- [ ] Support global configuration of pipeline policies:
  - [x] Logging: log level, logger implementation
  - [x] Telemetry: (PR #355)
  - [ ] Retry: (Issue #356)
  - [x] Timeout: (PR #345)

**Comment by bsiegel** [comment]
Closing this issue as the last remaining work is tracked in #356
