### ISSUE TITLE
[BUG] Crashed AzureCommunicationCalling ACSCallClient

### ISSUE THREAD

**Issue by InnaBlack** [Azure/azure-sdk-for-ios#1511]
**Describe the bug**
Crashed: com.apple.root.default-qos
0  AzureCommunicationCalling      0x99520 sam_initialization_options::StdoutLogging() const + 6
1  AzureCommunicationCalling      0x72588 sam_call_client::CreateCallAgentInternal(IFactory&, sam_internal_token_provider*, rt::IntrusivePtr<sam_initialization_options>, sam_call_agent_options*, sam_call_agent**, bool) + 620
2  AzureCommunicationCalling      0x71ce0 sam_call_client_create_call_agent_common(sam_call_client*, sam_internal_token_provider*, sam_call_agent_options*, unsigned char, sam_call_agent**) + 308
3  AzureCommunicationCalling      0x17550 __117-[ACSCallClient createCallAgentWithCallKitWithTokenProvider:callAgentOptions:isCallKitEnabled:withCompletionHandler:]_block_invoke + 96
4  libdispatch.dylib              0x2460 _dispatch_call_block_and_release + 32
5  libdispatch.dylib              0x3f88 _dispatch_client_callout + 20
6  libdispatch.dylib              0x7074 _dispatch_queue_override_invoke + 788
7  libdispatch.dylib              0x15a6c _dispatch_root_queue_drain + 396
8  libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
9  libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
10 libsystem_pthread.dylib        0xb98 start_wqthread + 8

**Comment by InnaBlack** [comment]
And one more crash

Crashed: com.apple.root.default-qos
0  libc++.1.dylib                 0xfe94 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 16
1  AzureCommunicationCalling      0x93f08 Factory::GetSkyLib() + 220
2  AzureCommunicationCalling      0x94580 Factory::CreateDefaultTelemetryProvider() + 148
3  AzureCommunicationCalling      0x729f0 sam_call_client::CreateCallAgentInternal(IFactory&, sam_internal_token_provider*, rt::IntrusivePtr<sam_initialization_options>, sam_call_agent_options*, sam_call_agent**, bool) + 1748
4  AzureCommunicationCalling      0x71c58 sam_call_client_create_call_agent_common(sam_call_client*, sam_internal_token_provider*, sam_call_agent_options*, unsigned char, sam_call_agent**) + 172
5  AzureCommunicationCalling      0x17550 __117-[ACSCallClient createCallAgentWithCallKitWithTokenProvider:callAgentOptions:isCallKitEnabled:withCompletionHandler:]_block_invoke + 96
6  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
8  libdispatch.dylib              0x6858 _dispatch_queue_override_invoke + 720
9  libdispatch.dylib              0x13b94 _dispatch_root_queue_drain + 340
10 libdispatch.dylib              0x1439c _dispatch_worker_thread2 + 172
11 libsystem_pthread.dylib        0x1dd4 _pthread_wqthread + 224
12 libsystem_pthread.dylib        0x193c start_wqthread + 8

**Comment by InnaBlack** [comment]
This is happen from   'AzureCommunicationCalling', '2.2.0'

**Comment by tjprescott** [comment]
@raosanat can you please triage and investigate?

**Comment by lucianopa-msft** [comment]
We are looking into these old bugs and closing, can you please try with latest (2.10) version and if still reproducible, feel free to reopen.
