### ISSUE TITLE
[BUG] AzureCommunicationCommon/AzureCommunicationCommon-Swift.h' file not found

### ISSUE THREAD

**Issue by HuyVuong1121** [Azure/azure-sdk-for-ios#1517]
**Describe the bug**
When using the pod static framework, the file 'AzureCommunicationCommon/AzureCommunicationCommon-Swift.h' is not found.

**To Reproduce**

1. Init PodFile
> 
> platform :ios, '13.0'
> target 'DemoAzureFW' do
>   pod 'AzureCommunicationCalling', '2.3.0-beta.4', :modular_headers => true
> end

> 
2. Pod install
3. Open .xcworkspace
4. Build

***Code Snippet***
<img width="1273" alt="Screenshot 2023-04-11 at 16 53 52" src="https://user-images.githubusercontent.com/20431860/231125125-6d3679c1-62a6-44c7-8d09-51a822599288.png">

**Expected behavior**
No error

**Screenshots**
![Screen Shot 2023-04-11 at 15 49 39](https://user-images.githubusercontent.com/20431860/231107877-12a02332-c781-4170-b085-84e93163ad72.png)

**Setup (please complete the following information):**
 - OS: [MacOS: 12.5.1]
 - IDE : [Xcode: Version 13.4.1]
 - Version of the Library used: 2.3.0-beta.4

**Comment by JasonWeinzierl** [comment]
I also have this issue.  macOS 13.3.1, Xcode 14.3, library version 2.3.0.

**Comment by lucianopa-msft** [comment]
Closing this as it is something discussed and resolved as unsupported in https://github.com/Azure/azure-sdk-for-ios/issues/1539
