### ISSUE TITLE
[FEATURE REQ] Add option to not ring via CallKit

### ISSUE THREAD

**Issue by JasonWeinzierl** [Azure/azure-sdk-for-ios#1560]
**Is your feature request related to a problem? Please describe.**

If an application is using Teams interop to receive incoming Teams calls, CallKit will ring the iPhone as expected.  However, if the user has installed both the Teams interop application using this SDK, *as well as* the official Teams iOS app, then both applications will ring via CallKit.  This may confuse users.

**Describe the solution you'd like**

Provide a flag in `CallKitOptions` to disable incoming call notifications.

**Describe alternatives you've considered**

- Disable CallKit functionality completely (don't pass in `CallKitOptions` when creating a `CallAgent`).  Not too appealing because then you lose all the benefits of CallKit.
- Manually implement CallKit and don't trigger incoming call notifications.  Would take extra work to maintain, considering how CallKit is already implemented in this SDK for us.

**Additional context**

N/A

**Information Checklist**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by tjprescott** [comment]
@raosanat can you take a look?
