### ISSUE TITLE
[BUG] call.hangUp doesn't cancel outgoing Ringing calls.

### ISSUE THREAD

**Issue by JasonWeinzierl** [Azure/azure-sdk-for-ios#1562]
**Describe the bug**

In AzureCommunicationCalling, `call.hangUp()` does not cancel outgoing "Ringing" calls.  Awaiting `hangUp` will pause execution and either throw an error on repeated attempts, or not return until call timeout.  The callee's `IncomingCall` delegate will not fire the `didEnd` event, which means user may incorrectly be able to accept/reject calls, which immediately ends the call for both parties.

***Exception or Stack Trace***

Repeatedly attempting to hang up seems to cause CallKit errors:

```
Error Domain=com.apple.CallKit.error.requesttransaction Code=4 "(null)"
```

After the callee rejects/accepts or timeout occurs, this error is thrown:

```
Error Domain=ACSCallingShared Code=1 "Failed" UserInfo={NSLocalizedDescription=Failed}
```

**To Reproduce**

1. Launch your [quickstart demo app](https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-video-calling)
2. Make an outgoing call
3. Press "End Call" while the call state is "Ringing".
4. The call will not end, and the callee's IncomingCall delegate will not fire `didEnd`.
5. The call will eventually timeout if the callee takes no action.

***Code Snippet***

The provided quickstart has this issue.

https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-video-calling

**Expected behavior**

`call.hangUp()` should cancel outgoing calls like this library's Android equivalent.

**Screenshots**

N/A

**Setup (please complete the following information):**

 - iOS: 16.5
 - Xcode: 14.3.1
 - AzureCommunicationCalling: 2.3.0-beta.5, 2.4.0, 2.4.1

**Additional context**

N/A

**Information Checklist**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tjprescott** [comment]
@raosanat can you please take a look?

**Comment by raosanat** [comment]
Hi, thanks for reporting the issue. We have a fix for this and will be releasing in the next release soon.
