### ISSUE TITLE
[BUG] ChatClient startPushNotifications "Service returned invalid status code 400"

### ISSUE THREAD

**Issue by Calfredop** [Azure/azure-sdk-for-ios#1572]
**Describe the bug**

I'm working on a React Native app that needs to implemet Azure Communication Chat but I can't register the device with 
the startPushNotifications method as instructed on the sample provided with the documentation.

***Exception or Stack Trace***

This is the error throwed by the library

`error: client("Failed to start push notifications", Optional(AzureCore.AzureError.client("Failed to start push notifications", Optional(AzureCore.AzureError.client("Registration request failed.", Optional(AzureCore.AzureError.client("Registration request failed.", Optional(AzureCore.AzureError.service("Service returned invalid status code [400]", nil)))))))))]}`

**To Reproduce**

I've made a Swift native module that should take care of enabling push notification via chatclient. Therefore I've followed the instructions to integrate the iOS sdk on the native part of my app with partial success.

What is working:

- Communication between React Native components and native Swift module 
- ChatClient generation (I can list threads)

What is not working:

When I call the `chatclient.startPushNotifications` method, passig of course the correct `deviceToken`, I get an error and the push notifications don't get enabled.

***Code Snippet***

`chatClient.startPushNotifications(deviceToken: deviceToken) { result in
            switch result {
            case .success:
               resolve("startPushNotifications done")
            case let .failure(error):
               reject("0", "startPushNotifications error: \(error)",nil)
            }
            semaphore.signal()
        }`

**Expected behavior**

Since the deviceToken is generated correctly and successfully used for other remote push notifications services, it should register just fine for Azure Chat.

**Setup (please complete the following information):**
 - OS: iOS 13 (emulator)
 - IDE : XCode/VS Code
 -  AzureCommunicationChat 1.3.1

**Comment by Calfredop** [comment]
I've managed to find where the problem. I had to log the calls to the Azure backend because the default error is not clear and I had to read the response via log.
So the problem seems to be the token lenght, which on my iOS emulator exceeds the Azure backend limit of 100 characters.
It's stated in the Apple documentation that the lenght of the token is variable so I think that this check should be taken out cause it might break the on real device implementatio too. Also, working on the real device is not as practical as on the emulator.

**Comment by tjprescott** [comment]
@angellan-msft @LuChen-Microsoft can you please take a look at this issue?

**Comment by angellan-msft** [comment]
We are looking into this issue.

**Comment by angellan-msft** [comment]
Hi @Calfredop , how do you find the issue is because of "the token length"? Could you share any log you are seeing?

**Comment by Calfredop** [comment]
> Hi @Calfredop , how do you find the issue is because of "the token length"? Could you share any log you are seeing?

Hello @angellan-msft. Since error handling is muted in the SDK (the comment states that is so to avoid handling XML responses), I've simply logged the full Azure server response. So instead of a generic errror with a 400 status code, I was able to read the actual server message.
I don't remember exactly the message, but it surely had the "length" word and the "100" number. I think you can easily reproduce this behavior by sending a 101+ lenght string as deviceToken in the startPushNotifications method.

**Comment by angellan-msft** [comment]
Thanks for the response. We are checking for you.

**Comment by angellan-msft** [comment]
is this an issue when you use real device?

**Comment by Calfredop** [comment]
Hello,
I'm facing the issue only on my iOS emulator because it has a 160 character token length. [Apple documentation](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application) states that the size of the token is not fixed. In my opinion this issue might suddenly break iOS push notification in the coming operating system or hardware releases. I have also reported the founding to MS MSRC but they didn't recognized it as an issue.
A little more details:

- The full error states "APNS path exceeds maximum acceptable length of 100 characters"
- The Azure Communication API endpoint is https://edge.skype.com/registrar/prod/v2/registrations endpoint

**Comment by angellan-msft** [comment]
We recommend our customers to use IOS real device for Push Notification. This is not recognized as an issue.
