### ISSUE TITLE
AzureCommunicationCalling watchOS Support

### ISSUE THREAD

**Issue by MaxMilon** [Azure/azure-sdk-for-ios#1610]
**Is your feature request related to a problem? Please describe.**
I would like to use the AzureCommunicationCalling library on the watchOS platform.

**Describe the solution you'd like**
AzureCommunicationCalling library should support the watchOS platform.

**Describe alternatives you've considered**
An alternative solution would be to fork the iOS project and add the watchOS support there. However, as explained in #1478 , there is no plan to make the AzureCommunicationCalling project open source.

**Comment by tjprescott** [comment]
@raosanat can you please comment here?

**Comment by raosanat** [comment]
Hi, we currently do not support armv7 binaries which watchOS needs. We will look in to the timeline when we can add support for watchOS.
