### ISSUE TITLE
[BUG] ACSScreenShareOutgoingVideoStream vertical aspect ratio support

### ISSUE THREAD

**Issue by tsimafeiz** [Azure/azure-sdk-for-ios#1653]
**Describe the bug**
**`ACSScreenShareOutgoingVideoStream`** object doesn't support any format **`VideoStreamFormat`** which resolution has vertical aspect ratio. Stream just stops.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Initialise **`ACSScreenShareOutgoingVideoStream`** with **`RawOutgoingVideoStreamOptions`**, which includes **`VideoStreamFormat`** with vertical aspect ratio

***Code Snippet***
```
let horizontalFormat = VideoStreamFormat()
horizontalFormat.resolution = .hd
horizontalFormat.pixelFormat = .nv12
horizontalFormat.framesPerSecond = 30
horizontalFormat.stride1 = 1280
horizontalFormat.stride2 = 1280 / 2
        
let verticalFormat = VideoStreamFormat()
verticalFormat.width = 720
verticalFormat.height = 1280
verticalFormat.pixelFormat = .nv12
verticalFormat.framesPerSecond = 30
verticalFormat.stride1 = 720
verticalFormat.stride2 = 720 / 2

var videoStreamFormats: [VideoStreamFormat] = [VideoStreamFormat]()
videoStreamFormats.append(horizontalFormat)
videoStreamFormats.append(verticalFormat)

let rawOutgoingVideoOptions = RawOutgoingVideoStreamOptions()
rawOutgoingVideoOptions.formats = videoStreamFormats
return ScreenShareOutgoingVideoStream(videoStreamOptions: rawOutgoingVideoOptions)
```

**Expected behavior**
Any aspect ratio and resolution up to 1080p should be supported as it was documented on [this](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access?pivots=platform-ios#screenshare-video) page

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOS 17.0.3
 - IDE : Xcode 15.0.0
 - Version of the Library used: 2.5.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tjprescott** [comment]
@raosanat can you please take a look?

**Comment by raosanat** [comment]
@tsimafeiz can you confirm if on the recipient side do you see no video at all or you see a video with black screen ? Do you get the video streams for the Remote Participant on the recipient side ?

**Comment by tsimafeiz** [comment]
@raosanat On the recipient side there's no video at all

**Comment by yassirbisteni** [comment]
portrait video frames are supported for screen share we already confirm that with you
