### ISSUE TITLE
[BUG] ACSRawIncomingVideoStream CVPixelBuffer glitches

### ISSUE THREAD

**Issue by tsimafeiz** [Azure/azure-sdk-for-ios#1654]
**Describe the bug**
CVPixelBuffer glitches and shows artefacts when resolution width of the **`ACSRawIncomingVideoStream`** isn't multiple of 16

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Send outgoing stream (could be any stream type, raw or not) of any resolution, which width will not be multiple of 16 (e.g. 540x960)

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Stream should look exactly the same as what we've sent as OutgoingVideoStream

**Screenshots**
https://github.com/Azure/azure-sdk-for-ios/assets/141160531/52221a3e-5add-41da-ae9e-b211caf64c90
<img width="154" alt="screenshot with glitching CVPixelBuffer" src="https://github.com/Azure/azure-sdk-for-ios/assets/141160531/17f3ef28-2f25-4fef-a6cf-c5050f11c8e4">

**Setup (please complete the following information):**
 - OS: [e.g. iOS] iOS 16.6.1
 - IDE : [e.g. IntelliJ] Xcode 14.3.1
 - Version of the Library used 2.5.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tjprescott** [comment]
@raosanat can you please take a look?

**Comment by tsimafeiz** [comment]
**Additional context**
The problem appears both when we're using AVFoundation with `AVSampleBufferDisplayLayer` and Metal with `MTKView` to render received CVPixelBuffer from Azure SDK

**Comment by yassirbisteni** [comment]
Could you please try this app on your end and lets us know if that works on your devices

 https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/raw-video

**Comment by tsimafeiz** [comment]
Thanks for the answer!
I've tried test app from shared link, but unfortunately this issue could be reproduced here too:

https://github.com/Azure/azure-sdk-for-ios/assets/141160531/13da2b5d-4595-406b-b099-8e932f8c3fc5

To reproduce it I used Microsoft teams(App Store version) from my iPhone 13 Pro Max, iOS 17.3.1

**Comment by tsimafeiz** [comment]
**Additional info:**
On this video you can see 3 opened application. From left to right: Raw-Video test app on simulator, Teams with opened meeting and our demo application, which is now showing how buffer looks like on our side before we send it

https://github.com/Azure/azure-sdk-for-ios/assets/141160531/b673f10d-e93b-4a8a-a7f3-568ec6511259
