### ISSUE TITLE
[BUG] Push Notifications: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by mattials** [Azure/azure-sdk-for-ios#1672]
**Describe the bug**
Encountered the error message: "'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead." in ApplicationUtil.swift line 49 -> return UIApplication.shared

***Exception or Stack Trace***
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

**To Reproduce**
Followed the Microsoft Azure tutorial [link](https://learn.microsoft.com/en-us/azure/communication-services/tutorials/add-chat-push-notifications#2---advanced-version) for integrating push notifications into a chat application.
Encountered the error message: "'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead."

***Code Snippet***
ApplicationUtil.swift line 49 -> return UIApplication.shared

**Expected behavior**
Successful compilation without errors on ./add-chat-push-notifications in xcode 15.

**Screenshots**
<img width="1128" alt="Issue" src="https://github.com/Azure/azure-sdk-for-ios/assets/119877139/dfc12127-5838-478f-aa9e-1a9773105da4">

**Setup (please complete the following information):**
 - OS: iOS 17.0.2
 - IDE : xCode 15
 - pod 'AzureCommunicationChat', '~> 1.3.3'

**Additional context**
Encountered the same issue in both a direct integration into the chat project and when using the Microsoft-provided example project [link](https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-chat-push-notifications). The issue appears to be related to the AzureCore dependency, and a possible solution was suggested in the Apple Developer Forums [link](https://developer.apple.com/forums/thread/685369), recommending the use of @available(iOSApplicationExtension, unavailable). This change may need to be implemented in the Azure SDK to resolve the issue.

https://github.com/Azure-Samples/communication-services-ios-quickstarts/issues/70

**Comment by tjprescott** [comment]
@angellan-msft can you please take a look.

**Comment by angellan-msft** [comment]
@mattials , I just returned to office and will look into it next week.

**Comment by mattials** [comment]
@angellan-msft @tjprescott I created a PR, I tested locally to fix the error, can you check it please 🙏 

https://github.com/Azure/azure-sdk-for-ios/pull/1673

**Comment by angellan-msft** [comment]
Note: I'll keeping providing the update in the PR created by the customer.
PR link: https://github.com/Azure/azure-sdk-for-ios/pull/1673

**Comment by mattials** [comment]
The workaround: https://github.com/Azure/azure-sdk-for-ios/pull/1673#issuecomment-1888098995

**Comment by tjprescott** [comment]
Fixed in #1673.
