### ISSUE TITLE
Module cannot be imported by newer swift compiler, please enable Build Libraries for Distribution

### ISSUE THREAD

**Issue by borland** [Azure/azure-sdk-for-ios#174]
I downloaded the Azure SDK binary release from here: https://github.com/Azure/azure-sdk-for-ios/releases

I'm building a macOS command line utility using XCode 11.2.1

I added AzureCore and AzureStorage to my project, then added `import AzureCore` to my main.swift file

I receive the following error

    Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler: /Users/orione/Dev/MyApp/external/AzureCore.framework/Modules/AzureCore.swiftmodule/x86_64.swiftmodule

Swift 5 provides module stability, however the modules must explicitly opt into this by setting `BUILD_LIBRARY_FOR_DISTRIBUTION = YES;` in the pbxproj (or associated GUI setting)

https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/58656323?noredirect=1#comment105165590_58656323

It looks like the Azure libraries aren't compiled with this flag. (Evidence is that under the `AzureCore.swiftmodule` folder there is a .swiftdoc and a .swiftmodule but NOT a .swiftinterface, which is required for module stability)

**Comment by bsiegel** [comment]
Closing as wontfix, we are preparing for a release of the Track 2 SDK libraries which are based on a different codebase. We will ensure that Track 2 SDK libraries include this build setting, thank you for the report!
