### ISSUE TITLE
[BUG] Microphone Indicator is visible even the call is muted

### ISSUE THREAD

**Issue by eskizyen** [Azure/azure-sdk-for-ios#1767]
**Describe the bug**
Orange microphone indicator is always visible after unmuting and muting the call again.

**To Reproduce**
1. Accept an incoming call with `outgoingAudioOptions` muted. Microphone indicator is not visible.
2. Unmute call. Microphone indicator is visible.
3. Mute it again. Microphone indicator is visible.

***Code Snippet***
```
let options = AcceptCallOptions()
let audioOptions = OutgoingAudioOptions()
audioOptions.muted = true
options.outgoingAudioOptions = audioOptions

incomingCall?.accept(options: options) { }

call?.unmuteOutgoingAudio(completionHandler: { })
call?.muteOutgoingAudio(completionHandler: { })
```

**Expected behavior**
Orange microphone indicator should be gone when call is muted.

**Setup (please complete the following information):**
 - OS: iOS 17.4.1
 - IDE : Xcode
 - 2.9.0

**Additional context**
It is tested with several devices, iOS versions.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by tjprescott** [comment]
@raosanat can you please take a look?

**Comment by lucianopa-msft** [comment]
Hi @eskizyen,
Are you using CallKit? Either [via SDK](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/callkit-integration) or implementing by yourself? 

> Orange microphone indicator should be gone when call is muted.

That behavior is only present if we signal CallKit that call is muted, so in that case if you use call kit with SDK you would observe correct behavior.

**Comment by eskizyen** [comment]
Thanks @lucianopa-msft, unfortunately using CallKit is not an option for me.

I think the real problem here is SDK still processes microphone input even the call is muted ([speakingWhileMicrophoneIsMuted](https://learn.microsoft.com/en-us/javascript/api/azure-communication-services/%40azure/communication-calling/latestmediadiagnostics?view=azure-communication-services-js#@azure-communication-calling-latestmediadiagnostics-speakingwhilemicrophoneismuted)). Is there any way to disable this?

I am able to override this behaviour using [AVAudioApplication.shared.setInputMuted(Bool)](https://developer.apple.com/documentation/avfaudio/avaudioapplication/4144306-setinputmuted), yet this class is introduced in iOS 17.

**Comment by lucianopa-msft** [comment]
> I think the real problem here is SDK still processes microphone input even the call is muted ([speakingWhileMicrophoneIsMuted](https://learn.microsoft.com/en-us/javascript/api/azure-communication-services/%40azure/communication-calling/latestmediadiagnostics?view=azure-communication-services-js#@azure-communication-calling-latestmediadiagnostics-speakingwhilemicrophoneismuted)). Is there any way to disable this?
> 

Not through our APIs at the moment there isn't, and we cannot really change this behavior on mute action because we need mic input for [speakingWhileMicrophoneIsMuted](https://learn.microsoft.com/en-us/javascript/api/azure-communication-services/%40azure/communication-calling/latestmediadiagnostics?view=azure-communication-services-js#@azure-communication-calling-latestmediadiagnostics-speakingwhilemicrophoneismuted) UFD.

> I am able to override this behaviour using [AVAudioApplication.shared.setInputMuted(Bool)](https://developer.apple.com/documentation/avfaudio/avaudioapplication/4144306-setinputmuted), yet this class is introduced in iOS 17.

Likely there is a way to do that in older OSes? Using a different API?

**Comment by eskizyen** [comment]
> Likely there is a way to do that in older OSes? Using a different API?

I couldn't find anything so far. Thanks for your time.

**Comment by lucianopa-msft** [comment]
As there is no action we can provide in this case, let's close this for now @eskizyen if you still think we can provide any assistance in this scenario feel free to reopen or open another issue if you need more support regarding other issues :)
