### ISSUE TITLE
[BUG] Bot response cuts in between while using AzureCommunicationCalling

### ISSUE THREAD

**Issue by manojsharmadcx** [Azure/azure-sdk-for-ios#1837]
**Describe the bug**
I am calling a phone number using AzureCommunicationCalling SDK(1.0.0) by following links [https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/getting-started-with-calling?tabs=uwp&pivots=platform-ios](url), [https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/telephony/pstn-call?pivots=platform-ios](url). The callee phone number is tied to a virtual bot which starts responding once the call is established. However, the response speech from bot get's cut off in between before getting completed.

***Exception or Stack Trace***
NO traces available

**To Reproduce**
NA

***Code Snippet***
 ```
 func initiateCall() {
        guard let callAgent = callAgent else {
            print("@@ ERROR: Call agent is not available")
            return
        }
        
        let startCallOptions = StartCallOptions()
        startCallOptions.alternateCallerId = PhoneNumberIdentifier(phoneNumber: self.caller)
        callAgent.startCall(participants: [PhoneNumberIdentifier(phoneNumber: self.callee)], options: startCallOptions) { (call, error) in
            if let error = error {
                print("@@ Failed to get call object: \(error.localizedDescription)")
            } else {
                self.call = call
                print("@@ Call object created successfully")
            }
        }
    }
```

**Expected behavior**
Complete bot responses should be delivered during conversation

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS:  iOS
 - IDE : XCode 15.4
 - AzureCommunicationCalling 1.0.0

**Additional context**
Tried upgrading to 2.11.0 but ran into another issue.

**Comment by manojsharmadcx** [comment]
Hi @raosanat, would you be able to help on this please. The response from other side in case of bot gets cut in between when using iOS SDK. Tried after upgrading to AzureCommunicationCaliing 2.11.0 as well, but the issue still persists. However, same thing works fine while trying with JavaScript SDK mentioned here - [https://github.com/Azure-Samples/communication-services-javascript-quickstarts/tree/main/add-1-on-1-phone-calling](url)

**Comment by raosanat** [comment]
@manojsharmadcx i am not following completely the scenario here. You are trying to call a phone number and the response gets cut in between.
1. When you say it "cuts in between" means the call gets dropped ?
2. What happens if you call any other phone number , like a normal PSTN number ?

**Comment by xumo-95** [comment]
Closing due to no response. Please feel free to reopen it if there's any updates.
