### ISSUE TITLE
How to provision device with x509

### ISSUE THREAD

**Issue by Shahanshah-TA** [Azure/azure-sdk-for-ios#1845]
Hi
I need to provision device with x509 certificate, for that I am trying to use swift code in React Native. But there is multiple documentation present, some are deprecated, some doesn't support DPS. What I should do? which package should I use?
is there documentation available for provisioning with x509 in swift or React Native?

**Comment by Shahanshah-TA** [comment]
Hi @tjprescott @scbedd @benbp @weshaggard @azure-sdk @sima-zhu Can anyone please help

**Comment by tjprescott** [comment]
@Shahanshah-TA from your issue it's not clear how you are trying to use the Azure SDK for iOS. What documentation are you referring to?

**Comment by Shahanshah-TA** [comment]
@tjprescott as per this docs https://azure.github.io/azure-sdk-for-ios/ it have [AzureCommunicationChat](https://azure.github.io/azure-sdk-for-ios/AzureCommunicationChat/index.html) [AzureCommunicationCommon](https://azure.github.io/azure-sdk-for-ios/AzureCommunicationCommon/index.html) [AzureCommunicationUI](https://azure.github.io/azure-sdk-for-ios/AzureCommunicationUI/index.html) [AzureCommunicationUICalling](https://azure.github.io/azure-sdk-for-ios/AzureCommunicationUICalling/index.html) [AzureCommunicationUIChat](https://azure.github.io/azure-sdk-for-ios/AzureCommunicationUIChat/index.html)  [AzureCore](https://azure.github.io/azure-sdk-for-ios/AzureCore/index.html) [AzureAIVisionCore](https://azure.github.io/azure-sdk-for-ios/AzureAIVisionCore/index.html) [AzureAIVisionFace](https://azure.github.io/azure-sdk-for-ios/AzureAIVisionFace/index.html) but I want to provision device with x509 certificate as per this [docs](https://learn.microsoft.com/en-us/azure/iot-dps/how-to-control-access#certificate-based-authentication)
Thats what I am trying to understand that can I use this package to achieve this functionality because I cannot find that anywhere for iOS, like I found for Android [here](https://github.com/Azure/azure-iot-sdk-java/blob/main/provisioning/provisioning-device-client-samples/provisioning-X509-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningX509Sample.java).

**Comment by tjprescott** [comment]
@Shahanshah-TA thank you for the clarification. IoT Device Provisioning isn't part of the Azure SDK for iOS package and thus it's not possible using this SDK.

You might try posting this question to the azure-iot-sdk-java repo, as the service team might have a better idea how to accomplish what you want. However, I suspect that SDK is not intended for mobile _per se_ and that they won't have an iOS-specific solution.

In that case your best option in Swift would be to make calls directly against the REST API using the HTTP library of your choice and the REST API documentation you linked to.

**Comment by Shahanshah-TA** [comment]
@tjprescott I am facing one issue with REST API approach. The problem is I am unable to add certificate and private key to http request. I am able to fetch the certificate and private key from local storage but I am not sure how to add that in REST API. I am a React Native dev, so I am not that very proficient in swift, if you don't mind can you please help me with that.
In node I know we use `https.Agent` but I am not sure about Swift.

**Comment by tjprescott** [comment]
Unfortunately I can't help with that as this repo is for users of the AzureSDK swift package. The mechanism will depend on the service and the networking you use. 

However, if you are a react dev, have you considered just using the javascript SDKs?
https://www.npmjs.com/package/azure-iot-device
https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-sdks#azure-iot-hub-device-sdks

There's also a link to iOS samples using the C library that might be useful:
https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/ios/CocoaPods-Samples.md

**Comment by tjprescott** [comment]
Since this issue is not addressable by the AzureSDK for Swift, I'm closing it.
