### ISSUE TITLE
[BUG] App crashes when hangup the call

### ISSUE THREAD

**Issue by SarawutSr** [Azure/azure-sdk-for-ios#1849]
This issue is related to #1826 

After I tested with your new beta version, 2.13.0-beta.1. (As in above thread mentioned me to try with new beta version)
The application able to run on iOS 17.4 and render remote video stream properly.

But when I hang up the call, I got the error as I mentioned on above.
The logs and screen capture are on below

AzureCommunicationCalling`Video::onPropertyChange:
0x10a68a0a4 <+0>: sub sp, sp, #0xa0
0x10a68a0a8 <+4>: stp x22, x21, [sp, #0x70]
0x10a68a0ac <+8>: stp x20, x19, [sp, #0x80]
0x10a68a0b0 <+12>: stp x29, x30, [sp, #0x90]
0x10a68a0b4 <+16>: add x29, sp, #0x90
0x10a68a0b8 <+20>: mov x20, x3
0x10a68a0bc <+24>: mov x22, x2
0x10a68a0c0 <+28>: mov x21, x1
0x10a68a0c4 <+32>: mov x19, x0
0x10a68a0c8 <+36>: adrp x8, 7714
0x10a68a0cc <+40>: ldr x8, [x8, #0x738]
0x10a68a0d0 <+44>: ldr x8, [x8]
0x10a68a0d4 <+48>: stur x8, [x29, #-0x28]
0x10a68a0d8 <+52>: cbz x0, 0x10a68a0ec ; <+72>
0x10a68a0dc <+56>: ldr x8, [x19]
-> 0x10a68a0e0 <+60>: ldur x8, [x8, #-0x18]
0x10a68a0e4 <+64>: add x0, x19, x8
0x10a68a0e8 <+68>: bl 0x10bd4ff38 ; rt::intrusive_ptr_add_ref(rt::IReferenceCountable const*)
0x10a68a0ec <+72>: ldr w8, [x19, #0x88]
0x10a68a0f0 <+76>: cmp w8, w21
0x10a68a0f4 <+80>: b.ne 0x10a68a14c ; <+168>
0x10a68a0f8 <+84>: cmp w22, #0x209
0x10a68a0fc <+88>: b.ne 0x10a68a338 ; <+660>
0x10a68a100 <+92>: adrp x22, 8439
0x10a68a104 <+96>: add x22, x22, #0x8d8 ; g_aufLogComponent
0x10a68a108 <+100>: ldr x21, [x22]
0x10a68a10c <+104>: ldr w8, [x21]
0x10a68a110 <+108>: cmp w8, #0x32
0x10a68a114 <+112>: b.gt 0x10a68a268 ; <+452>
0x10a68a118 <+116>: add x8, sp, #0x18
0x10a68a11c <+120>: mov x0, x19
0x10a68a120 <+124>: bl 0x10a689f18 ; Video::GetCorrelationId()
0x10a68a124 <+128>: cmp w20, #0x9
0x10a68a128 <+132>: b.hi 0x10a68a1ec ; <+328>
0x10a68a12c <+136>: adrp x8, 7781
0x10a68a130 <+140>: add x8, x8, #0x7b8 ; typeinfo for std::__1::__bind<void (Video::)(unsigned int, PROPKEY, unsigned int, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator>), Video, std::__1::placeholders::__ph<1> const&, std::__1::placeholders::__ph<2> const&, std::__1::placeholders::__ph<3> const&, std::__1::placeholders::__ph<4> const&> + 24
0x10a68a134 <+144>: ldr x8, [x8, w20, sxtw https://github.com/Azure/azure-sdk-for-ios/issues/3]
0x10a68a138 <+148>: ldrsb w10, [x19, #0x67]
0x10a68a13c <+152>: tbnz w10, #0x1f, 0x10a68a1fc ; <+344>
0x10a68a140 <+156>: add x9, x19, #0x50
0x10a68a144 <+160>: and x10, x10, #0xff
0x10a68a148 <+164>: b 0x10a68a200 ; <+348>
0x10a68a14c <+168>: adrp x8, 8439
0x10a68a150 <+172>: nop
0x10a68a154 <+176>: ldr x20, [x8, #0x8d8]
0x10a68a158 <+180>: ldr w8, [x20]
0x10a68a15c <+184>: cmp w8, #0x32
0x10a68a160 <+188>: b.gt 0x10a68a338 ; <+660>
0x10a68a164 <+192>: add x8, sp, #0x18
0x10a68a168 <+196>: mov x0, x19
0x10a68a16c <+200>: bl 0x10a689f18 ; Video::GetCorrelationId()
0x10a68a170 <+204>: ldrsb w9, [x19, #0x67]
0x10a68a174 <+208>: tbnz w9, #0x1f, 0x10a68a184 ; <+224>
0x10a68a178 <+212>: add x8, x19, #0x50
0x10a68a17c <+216>: and x9, x9, #0xff
0x10a68a180 <+220>: b 0x10a68a188 ; <+228>
0x10a68a184 <+224>: ldp x8, x9, [x19, #0x50]
0x10a68a188 <+228>: ldrb w10, [sp, #0x2f]
0x10a68a18c <+232>: sxtb w11, w10
0x10a68a190 <+236>: ldp x12, x13, [sp, #0x18]
0x10a68a194 <+240>: cmp w11, #0x0
0x10a68a198 <+244>: add x11, sp, #0x18
0x10a68a19c <+248>: csel x11, x12, x11, lt
0x10a68a1a0 <+252>: csel x10, x13, x10, lt
0x10a68a1a4 <+256>: stp x9, x11, [sp, #0x40]
0x10a68a1a8 <+260>: str x10, [sp, #0x50]
0x10a68a1ac <+264>: mov w9, #0x8803
0x10a68a1b0 <+268>: movk w9, #0x1, lsl https://github.com/Azure/azure-sdk-for-ios/issues/16
0x10a68a1b4 <+272>: stp x9, x8, [sp, #0x30]
0x10a68a1b8 <+276>: str w21, [sp, #0x58]
0x10a68a1bc <+280>: adrp x4, 7443
0x10a68a1c0 <+284>: add x4, x4, #0x624 ; "%s::OnPropertyChange, preview videoId: %s, returning because msrtc videoStatus belongs to a different videoId: %d"
0x10a68a1c4 <+288>: add x5, sp, #0x30
0x10a68a1c8 <+292>: mov x0, x20
0x10a68a1cc <+296>: mov x1, x19
0x10a68a1d0 <+300>: mov w2, #0x6a32
0x10a68a1d4 <+304>: mov w3, #0x0
0x10a68a1d8 <+308>: bl 0x10bd842d4 ; auf::LogComponent::log(void const*, unsigned int, unsigned int, char const*, auf::LogArgs const&)
0x10a68a1dc <+312>: ldrsb w8, [sp, #0x2f]
0x10a68a1e0 <+316>: tbz w8, #0x1f, 0x10a68a338 ; <+660>
0x10a68a1e4 <+320>: ldr x0, [sp, #0x18]
0x10a68a1e8 <+324>: b 0x10a68a2a8 ; <+516>
0x10a68a1ec <+328>: adrp x8, 7444
0x10a68a1f0 <+332>: add x8, x8, #0xa34 ; "INVALID_ENUM_VALUE"
0x10a68a1f4 <+336>: ldrsb w10, [x19, #0x67]
0x10a68a1f8 <+340>: tbz w10, #0x1f, 0x10a68a140 ; <+156>
0x10a68a1fc <+344>: ldp x9, x10, [x19, #0x50]
0x10a68a200 <+348>: ldrb w11, [sp, #0x2f]
0x10a68a204 <+352>: sxtb w12, w11
0x10a68a208 <+356>: ldp x13, x14, [sp, #0x18]
0x10a68a20c <+360>: cmp w12, #0x0
0x10a68a210 <+364>: add x12, sp, #0x18
0x10a68a214 <+368>: csel x12, x13, x12, lt
0x10a68a218 <+372>: csel x11, x14, x11, lt
0x10a68a21c <+376>: stp x10, x12, [sp, #0x40]
0x10a68a220 <+380>: mov w10, #0xa0000
0x10a68a224 <+384>: mov w12, #0x8803
0x10a68a228 <+388>: movk w12, #0x1, lsl https://github.com/Azure/azure-sdk-for-ios/issues/16
0x10a68a22c <+392>: orr x10, x12, x10
0x10a68a230 <+396>: stp x10, x9, [sp, #0x30]
0x10a68a234 <+400>: stp x11, x8, [sp, #0x50]
0x10a68a238 <+404>: adrp x4, 7443
0x10a68a23c <+408>: add x4, x4, #0x696 ; "%s::OnPropertyChange, videoId: %s, msrtc videoStatus: %s"
0x10a68a240 <+412>: add x5, sp, #0x30
0x10a68a244 <+416>: mov x0, x21
0x10a68a248 <+420>: mov x1, x19
0x10a68a24c <+424>: mov w2, #0x7a32
0x10a68a250 <+428>: mov w3, #0x0
0x10a68a254 <+432>: bl 0x10bd842d4 ; auf::LogComponent::log(void const*, unsigned int, unsigned int, char const*, auf::LogArgs const&)
0x10a68a258 <+436>: ldrsb w8, [sp, #0x2f]
0x10a68a25c <+440>: tbz w8, #0x1f, 0x10a68a268 ; <+452>
0x10a68a260 <+444>: ldr x0, [sp, #0x18]
0x10a68a264 <+448>: bl 0x10c0f31c4 ; symbol stub for: operator delete(void*)
0x10a68a268 <+452>: ldr x8, [x19, #0x80]
0x10a68a26c <+456>: cbz x8, 0x10a68a2b0 ; <+524>
0x10a68a270 <+460>: mov x8, sp
0x10a68a274 <+464>: mov x0, x19
0x10a68a278 <+468>: bl 0x10a689f18 ; Video::GetCorrelationId()
0x10a68a27c <+472>: str w20, [sp, #0x30]
0x10a68a280 <+476>: ldr x0, [x19, #0x80]
0x10a68a284 <+480>: cbz x0, 0x10a68a378 ; <+724>
0x10a68a288 <+484>: ldr x8, [x0]
0x10a68a28c <+488>: ldr x8, [x8, #0x30]
0x10a68a290 <+492>: add x1, sp, #0x30
0x10a68a294 <+496>: mov x2, sp
0x10a68a298 <+500>: blr x8
0x10a68a29c <+504>: ldrsb w8, [sp, #0x17]
0x10a68a2a0 <+508>: tbz w8, #0x1f, 0x10a68a338 ; <+660>
0x10a68a2a4 <+512>: ldr x0, [sp]
0x10a68a2a8 <+516>: bl 0x10c0f31c4 ; symbol stub for: operator delete(void*)
0x10a68a2ac <+520>: b 0x10a68a338 ; <+660>
0x10a68a2b0 <+524>: ldr x20, [x22]
0x10a68a2b4 <+528>: ldr w8, [x20]
0x10a68a2b8 <+532>: cmp w8, #0x32
0x10a68a2bc <+536>: b.gt 0x10a68a338 ; <+660>
0x10a68a2c0 <+540>: add x8, sp, #0x18
0x10a68a2c4 <+544>: mov x0, x19
0x10a68a2c8 <+548>: bl 0x10a689f18 ; Video::GetCorrelationId()
0x10a68a2cc <+552>: ldrsb w9, [x19, #0x67]
0x10a68a2d0 <+556>: tbnz w9, #0x1f, 0x10a68a2e0 ; <+572>
0x10a68a2d4 <+560>: add x8, x19, #0x50
0x10a68a2d8 <+564>: and x9, x9, #0xff
0x10a68a2dc <+568>: b 0x10a68a2e4 ; <+576>
0x10a68a2e0 <+572>: ldp x8, x9, [x19, #0x50]
0x10a68a2e4 <+576>: ldrb w10, [sp, #0x2f]
0x10a68a2e8 <+580>: sxtb w11, w10
0x10a68a2ec <+584>: ldp x12, x13, [sp, #0x18]
0x10a68a2f0 <+588>: cmp w11, #0x0
0x10a68a2f4 <+592>: add x11, sp, #0x18
0x10a68a2f8 <+596>: csel x11, x12, x11, lt
0x10a68a2fc <+600>: csel x10, x13, x10, lt
0x10a68a300 <+604>: mov w12, #0x8802
0x10a68a304 <+608>: stp x12, x8, [sp, #0x30]
0x10a68a308 <+612>: stp x9, x11, [sp, #0x40]
0x10a68a30c <+616>: str x10, [sp, #0x50]
0x10a68a310 <+620>: adrp x4, 7443
0x10a68a314 <+624>: add x4, x4, #0x6cf ; "%s::OnPropertyChange, videoId: %s, event not sent"
0x10a68a318 <+628>: add x5, sp, #0x30
0x10a68a31c <+632>: mov x0, x20
0x10a68a320 <+636>: mov x1, x19
0x10a68a324 <+640>: mov w2, #0x8532
0x10a68a328 <+644>: mov w3, #0x0
0x10a68a32c <+648>: bl 0x10bd842d4 ; auf::LogComponent::log(void const*, unsigned int, unsigned int, char const*, auf::LogArgs const&)
0x10a68a330 <+652>: ldrsb w8, [sp, #0x2f]
0x10a68a334 <+656>: tbnz w8, #0x1f, 0x10a68a1e4 ; <+320>
0x10a68a338 <+660>: ldr x8, [x19]
0x10a68a33c <+664>: ldur x8, [x8, #-0x18]
0x10a68a340 <+668>: add x0, x19, x8
0x10a68a344 <+672>: bl 0x10bd4ff44 ; rt::intrusive_ptr_release(rt::IReferenceCountable const*)
0x10a68a348 <+676>: ldur x8, [x29, #-0x28]
0x10a68a34c <+680>: adrp x9, 7714
0x10a68a350 <+684>: ldr x9, [x9, #0x738]
0x10a68a354 <+688>: ldr x9, [x9]
0x10a68a358 <+692>: cmp x9, x8
0x10a68a35c <+696>: b.ne 0x10a68a374 ; <+720>
0x10a68a360 <+700>: ldp x29, x30, [sp, #0x90]
0x10a68a364 <+704>: ldp x20, x19, [sp, #0x80]
0x10a68a368 <+708>: ldp x22, x21, [sp, #0x70]
0x10a68a36c <+712>: add sp, sp, #0xa0
0x10a68a370 <+716>: ret
0x10a68a374 <+720>: bl 0x10c0f332c ; symbol stub for: __stack_chk_fail
0x10a68a378 <+724>: bl 0x10bd9b084 ; std::__1::__throw_bad_function_call[abi:v160006](https://github.com/Azure/azure-sdk-for-ios/issues/1826)

**To Reproduce**

Xcode Version 15.4 (15F31d)

**Use one of the MS example projects**

https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-video-calling
https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/join-room-call

With AzureCommunicationCalling 2.13.0-beta.1
https://github.com/Azure/Communication/releases/tag/v2.13.0-beta.1

Run Xcode simulator with iOS 17.4 (either Debug or Release)

**Expected behavior**
The remote video stream would be smoothly render and hangup call properly.

<img width="1797" alt="Screenshot 2024-08-01 at 20 22 05" src="https://github.com/user-attachments/assets/577ef3b1-08bb-4116-a6fe-6f2cb4022eab">

**Comment by tjprescott** [comment]
@raosanat can you take a look?

**Comment by lucianopa-msft** [comment]
@SarawutSr I cannot repro this locally, can you add more details for the reproduction flow. I am using the https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-video-calling sample.

**Comment by SarawutSr** [comment]
> @SarawutSr I cannot repro this locally, can you add more details for the reproduction flow. I am using the https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-video-calling sample.

I use this project 
https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-video-calling
as a user app in iOS.

And this project 
https://github.com/Azure-Samples/communication-services-web-calling-hero
as admin app for admin staff.

I setup this project to enters to the same room id.
as picture on below.

![Screenshot 2024-08-02 at 09 21 55](https://github.com/user-attachments/assets/429233b6-7309-4eca-bd57-555b428fc3b6)

When I hang up the call on iOS, I got the error and iOS app look like pictures on below

![Screenshot 2024-08-02 at 09 22 13](https://github.com/user-attachments/assets/6513adbd-7ae3-49de-81ba-f43a76e596dd)

<img width="1507" alt="Screenshot 2024-08-02 at 09 22 31" src="https://github.com/user-attachments/assets/53576d91-f35f-4656-9944-4ec0584072af">


I did the screen recording on the simulator. 

https://github.com/user-attachments/assets/b6db5b11-5b46-4d0f-bedf-0403fe464388


This is the log from Xcode.
AzureCommunicationCalling`Video::onPropertyChange:
    0x10649e0a4 <+0>:   sub    sp, sp, #0xa0
    0x10649e0a8 <+4>:   stp    x22, x21, [sp, #0x70]
    0x10649e0ac <+8>:   stp    x20, x19, [sp, #0x80]
    0x10649e0b0 <+12>:  stp    x29, x30, [sp, #0x90]
    0x10649e0b4 <+16>:  add    x29, sp, #0x90
    0x10649e0b8 <+20>:  mov    x20, x3
    0x10649e0bc <+24>:  mov    x22, x2
    0x10649e0c0 <+28>:  mov    x21, x1
    0x10649e0c4 <+32>:  mov    x19, x0
    0x10649e0c8 <+36>:  adrp   x8, 7714
    0x10649e0cc <+40>:  ldr    x8, [x8, #0x738]
    0x10649e0d0 <+44>:  ldr    x8, [x8]
    0x10649e0d4 <+48>:  stur   x8, [x29, #-0x28]
    0x10649e0d8 <+52>:  cbz    x0, 0x10649e0ec           ; <+72>
    0x10649e0dc <+56>:  ldr    x8, [x19]
->  0x10649e0e0 <+60>:  ldur   x8, [x8, #-0x18]
    0x10649e0e4 <+64>:  add    x0, x19, x8
    0x10649e0e8 <+68>:  bl     0x107b63f38               ; rt::intrusive_ptr_add_ref(rt::IReferenceCountable const*)
    0x10649e0ec <+72>:  ldr    w8, [x19, #0x88]
    0x10649e0f0 <+76>:  cmp    w8, w21
    0x10649e0f4 <+80>:  b.ne   0x10649e14c               ; <+168>
    0x10649e0f8 <+84>:  cmp    w22, #0x209
    0x10649e0fc <+88>:  b.ne   0x10649e338               ; <+660>
    0x10649e100 <+92>:  adrp   x22, 8439
    0x10649e104 <+96>:  add    x22, x22, #0x8d8          ; g_aufLogComponent
    0x10649e108 <+100>: ldr    x21, [x22]
    0x10649e10c <+104>: ldr    w8, [x21]
    0x10649e110 <+108>: cmp    w8, #0x32
    0x10649e114 <+112>: b.gt   0x10649e268               ; <+452>
    0x10649e118 <+116>: add    x8, sp, #0x18
    0x10649e11c <+120>: mov    x0, x19
    0x10649e120 <+124>: bl     0x10649df18               ; Video::GetCorrelationId()
    0x10649e124 <+128>: cmp    w20, #0x9
    0x10649e128 <+132>: b.hi   0x10649e1ec               ; <+328>
    0x10649e12c <+136>: adrp   x8, 7781
    0x10649e130 <+140>: add    x8, x8, #0x7b8            ; typeinfo for std::__1::__bind<void (Video::*)(unsigned int, PROPKEY, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>), Video*, std::__1::placeholders::__ph<1> const&, std::__1::placeholders::__ph<2> const&, std::__1::placeholders::__ph<3> const&, std::__1::placeholders::__ph<4> const&> + 24
    0x10649e134 <+144>: ldr    x8, [x8, w20, sxtw #3]
    0x10649e138 <+148>: ldrsb  w10, [x19, #0x67]
    0x10649e13c <+152>: tbnz   w10, #0x1f, 0x10649e1fc   ; <+344>
    0x10649e140 <+156>: add    x9, x19, #0x50
    0x10649e144 <+160>: and    x10, x10, #0xff
    0x10649e148 <+164>: b      0x10649e200               ; <+348>
    0x10649e14c <+168>: adrp   x8, 8439
    0x10649e150 <+172>: nop    
    0x10649e154 <+176>: ldr    x20, [x8, #0x8d8]
    0x10649e158 <+180>: ldr    w8, [x20]
    0x10649e15c <+184>: cmp    w8, #0x32
    0x10649e160 <+188>: b.gt   0x10649e338               ; <+660>
    0x10649e164 <+192>: add    x8, sp, #0x18
    0x10649e168 <+196>: mov    x0, x19
    0x10649e16c <+200>: bl     0x10649df18               ; Video::GetCorrelationId()
    0x10649e170 <+204>: ldrsb  w9, [x19, #0x67]
    0x10649e174 <+208>: tbnz   w9, #0x1f, 0x10649e184    ; <+224>
    0x10649e178 <+212>: add    x8, x19, #0x50
    0x10649e17c <+216>: and    x9, x9, #0xff
    0x10649e180 <+220>: b      0x10649e188               ; <+228>
    0x10649e184 <+224>: ldp    x8, x9, [x19, #0x50]
    0x10649e188 <+228>: ldrb   w10, [sp, #0x2f]
    0x10649e18c <+232>: sxtb   w11, w10
    0x10649e190 <+236>: ldp    x12, x13, [sp, #0x18]
    0x10649e194 <+240>: cmp    w11, #0x0
    0x10649e198 <+244>: add    x11, sp, #0x18
    0x10649e19c <+248>: csel   x11, x12, x11, lt
    0x10649e1a0 <+252>: csel   x10, x13, x10, lt
    0x10649e1a4 <+256>: stp    x9, x11, [sp, #0x40]
    0x10649e1a8 <+260>: str    x10, [sp, #0x50]
    0x10649e1ac <+264>: mov    w9, #0x8803
    0x10649e1b0 <+268>: movk   w9, #0x1, lsl #16
    0x10649e1b4 <+272>: stp    x9, x8, [sp, #0x30]
    0x10649e1b8 <+276>: str    w21, [sp, #0x58]
    0x10649e1bc <+280>: adrp   x4, 7443
    0x10649e1c0 <+284>: add    x4, x4, #0x624            ; "%s::OnPropertyChange, preview videoId: %s, returning because msrtc videoStatus belongs to a different videoId: %d"
    0x10649e1c4 <+288>: add    x5, sp, #0x30
    0x10649e1c8 <+292>: mov    x0, x20
    0x10649e1cc <+296>: mov    x1, x19
    0x10649e1d0 <+300>: mov    w2, #0x6a32
    0x10649e1d4 <+304>: mov    w3, #0x0
    0x10649e1d8 <+308>: bl     0x107b982d4               ; auf::LogComponent::log(void const*, unsigned int, unsigned int, char const*, auf::LogArgs const&)
    0x10649e1dc <+312>: ldrsb  w8, [sp, #0x2f]
    0x10649e1e0 <+316>: tbz    w8, #0x1f, 0x10649e338    ; <+660>
    0x10649e1e4 <+320>: ldr    x0, [sp, #0x18]
    0x10649e1e8 <+324>: b      0x10649e2a8               ; <+516>
    0x10649e1ec <+328>: adrp   x8, 7444
    0x10649e1f0 <+332>: add    x8, x8, #0xa34            ; "INVALID_ENUM_VALUE"
    0x10649e1f4 <+336>: ldrsb  w10, [x19, #0x67]
    0x10649e1f8 <+340>: tbz    w10, #0x1f, 0x10649e140   ; <+156>
    0x10649e1fc <+344>: ldp    x9, x10, [x19, #0x50]
    0x10649e200 <+348>: ldrb   w11, [sp, #0x2f]
    0x10649e204 <+352>: sxtb   w12, w11
    0x10649e208 <+356>: ldp    x13, x14, [sp, #0x18]
    0x10649e20c <+360>: cmp    w12, #0x0
    0x10649e210 <+364>: add    x12, sp, #0x18
    0x10649e214 <+368>: csel   x12, x13, x12, lt
    0x10649e218 <+372>: csel   x11, x14, x11, lt
    0x10649e21c <+376>: stp    x10, x12, [sp, #0x40]
    0x10649e220 <+380>: mov    w10, #0xa0000
    0x10649e224 <+384>: mov    w12, #0x8803
    0x10649e228 <+388>: movk   w12, #0x1, lsl #16
    0x10649e22c <+392>: orr    x10, x12, x10
    0x10649e230 <+396>: stp    x10, x9, [sp, #0x30]
    0x10649e234 <+400>: stp    x11, x8, [sp, #0x50]
    0x10649e238 <+404>: adrp   x4, 7443
    0x10649e23c <+408>: add    x4, x4, #0x696            ; "%s::OnPropertyChange, videoId: %s, msrtc videoStatus: %s"
    0x10649e240 <+412>: add    x5, sp, #0x30
    0x10649e244 <+416>: mov    x0, x21
    0x10649e248 <+420>: mov    x1, x19
    0x10649e24c <+424>: mov    w2, #0x7a32
    0x10649e250 <+428>: mov    w3, #0x0
    0x10649e254 <+432>: bl     0x107b982d4               ; auf::LogComponent::log(void const*, unsigned int, unsigned int, char const*, auf::LogArgs const&)
    0x10649e258 <+436>: ldrsb  w8, [sp, #0x2f]
    0x10649e25c <+440>: tbz    w8, #0x1f, 0x10649e268    ; <+452>
    0x10649e260 <+444>: ldr    x0, [sp, #0x18]
    0x10649e264 <+448>: bl     0x107f071c4               ; symbol stub for: operator delete(void*)
    0x10649e268 <+452>: ldr    x8, [x19, #0x80]
    0x10649e26c <+456>: cbz    x8, 0x10649e2b0           ; <+524>
    0x10649e270 <+460>: mov    x8, sp
    0x10649e274 <+464>: mov    x0, x19
    0x10649e278 <+468>: bl     0x10649df18               ; Video::GetCorrelationId()
    0x10649e27c <+472>: str    w20, [sp, #0x30]
    0x10649e280 <+476>: ldr    x0, [x19, #0x80]
    0x10649e284 <+480>: cbz    x0, 0x10649e378           ; <+724>
    0x10649e288 <+484>: ldr    x8, [x0]
    0x10649e28c <+488>: ldr    x8, [x8, #0x30]
    0x10649e290 <+492>: add    x1, sp, #0x30
    0x10649e294 <+496>: mov    x2, sp
    0x10649e298 <+500>: blr    x8
    0x10649e29c <+504>: ldrsb  w8, [sp, #0x17]
    0x10649e2a0 <+508>: tbz    w8, #0x1f, 0x10649e338    ; <+660>
    0x10649e2a4 <+512>: ldr    x0, [sp]
    0x10649e2a8 <+516>: bl     0x107f071c4               ; symbol stub for: operator delete(void*)
    0x10649e2ac <+520>: b      0x10649e338               ; <+660>
    0x10649e2b0 <+524>: ldr    x20, [x22]
    0x10649e2b4 <+528>: ldr    w8, [x20]
    0x10649e2b8 <+532>: cmp    w8, #0x32
    0x10649e2bc <+536>: b.gt   0x10649e338               ; <+660>
    0x10649e2c0 <+540>: add    x8, sp, #0x18
    0x10649e2c4 <+544>: mov    x0, x19
    0x10649e2c8 <+548>: bl     0x10649df18               ; Video::GetCorrelationId()
    0x10649e2cc <+552>: ldrsb  w9, [x19, #0x67]
    0x10649e2d0 <+556>: tbnz   w9, #0x1f, 0x10649e2e0    ; <+572>
    0x10649e2d4 <+560>: add    x8, x19, #0x50
    0x10649e2d8 <+564>: and    x9, x9, #0xff
    0x10649e2dc <+568>: b      0x10649e2e4               ; <+576>
    0x10649e2e0 <+572>: ldp    x8, x9, [x19, #0x50]
    0x10649e2e4 <+576>: ldrb   w10, [sp, #0x2f]
    0x10649e2e8 <+580>: sxtb   w11, w10
    0x10649e2ec <+584>: ldp    x12, x13, [sp, #0x18]
    0x10649e2f0 <+588>: cmp    w11, #0x0
    0x10649e2f4 <+592>: add    x11, sp, #0x18
    0x10649e2f8 <+596>: csel   x11, x12, x11, lt
    0x10649e2fc <+600>: csel   x10, x13, x10, lt
    0x10649e300 <+604>: mov    w12, #0x8802
    0x10649e304 <+608>: stp    x12, x8, [sp, #0x30]
    0x10649e308 <+612>: stp    x9, x11, [sp, #0x40]
    0x10649e30c <+616>: str    x10, [sp, #0x50]
    0x10649e310 <+620>: adrp   x4, 7443
    0x10649e314 <+624>: add    x4, x4, #0x6cf            ; "%s::OnPropertyChange, videoId: %s, event not sent"
    0x10649e318 <+628>: add    x5, sp, #0x30
    0x10649e31c <+632>: mov    x0, x20
    0x10649e320 <+636>: mov    x1, x19
    0x10649e324 <+640>: mov    w2, #0x8532
    0x10649e328 <+644>: mov    w3, #0x0
    0x10649e32c <+648>: bl     0x107b982d4               ; auf::LogComponent::log(void const*, unsigned int, unsigned int, char const*, auf::LogArgs const&)
    0x10649e330 <+652>: ldrsb  w8, [sp, #0x2f]
    0x10649e334 <+656>: tbnz   w8, #0x1f, 0x10649e1e4    ; <+320>
    0x10649e338 <+660>: ldr    x8, [x19]
    0x10649e33c <+664>: ldur   x8, [x8, #-0x18]
    0x10649e340 <+668>: add    x0, x19, x8
    0x10649e344 <+672>: bl     0x107b63f44               ; rt::intrusive_ptr_release(rt::IReferenceCountable const*)
    0x10649e348 <+676>: ldur   x8, [x29, #-0x28]
    0x10649e34c <+680>: adrp   x9, 7714
    0x10649e350 <+684>: ldr    x9, [x9, #0x738]
    0x10649e354 <+688>: ldr    x9, [x9]
    0x10649e358 <+692>: cmp    x9, x8
    0x10649e35c <+696>: b.ne   0x10649e374               ; <+720>
    0x10649e360 <+700>: ldp    x29, x30, [sp, #0x90]
    0x10649e364 <+704>: ldp    x20, x19, [sp, #0x80]
    0x10649e368 <+708>: ldp    x22, x21, [sp, #0x70]
    0x10649e36c <+712>: add    sp, sp, #0xa0
    0x10649e370 <+716>: ret    
    0x10649e374 <+720>: bl     0x107f0732c               ; symbol stub for: __stack_chk_fail
    0x10649e378 <+724>: bl     0x107baf084               ; std::__1::__throw_bad_function_call[abi:v160006]()

**Comment by lucianopa-msft** [comment]
@SarawutSr Just an update, I have tried for a while now with a few different versions of ACS but no luck in repro this. We will continue looking, but if you have more info please let us know.

**Comment by SarawutSr** [comment]
> @SarawutSr Just an update, I have tried for a while now with a few different versions of ACS but no luck in repro this. We will continue looking, but if you have more info please let us know.

I will try to reproduce all on this again this weekend. If i found somethings, will let you know.

**Comment by lucianopa-msft** [comment]
I think we narrow down the issue and fixed a similar stack trace. 
Can you please verify with the `2.13.0-beta.2`, it should be fixed there.

**Comment by SarawutSr** [comment]
> I think we narrow down the issue and fixed a similar stack trace. Can you please verify with the `2.13.0-beta.2`? It should be fixed there.

Sure, I will try and let you know.

Thanks.

**Comment by SarawutSr** [comment]
> I think we narrow down the issue and fixed a similar stack trace. Can you please verify with the `2.13.0-beta.2`? It should be fixed there.

I can't install your latest beta version as show in picture.

platform :ios, '13.0'
use_frameworks!

#ACSFrameworkVersion = '2.13.0-beta.1'
ACSFrameworkVersion = '2.13.0-beta.2'

target 'iOSVideo' do
  pod 'AzureCommunicationCalling', ACSFrameworkVersion
end

post_install do |installer|
  app_project = Xcodeproj::Project.open(Dir.glob("*.xcodeproj")[0])
  app_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)']
          if ACSFrameworkVersion.include?('beta')
            config.build_settings['OTHER_SWIFT_FLAGS'] << '-D BETA'
          end
          app_project.save
        end
  end
end
~                                                                                                                                                                                                                                                                                                                                                
~                  

![Screenshot 2024-09-01 at 11 45 23](https://github.com/user-attachments/assets/fc492fa6-8f4e-4244-9a40-85fa57d1a425)

**Comment by SarawutSr** [comment]
> I think we narrow down the issue and fixed a similar stack trace. Can you please verify with the `2.13.0-beta.2`? It should be fixed there.

I already tested in my project.
It seems good. It does not have any errors as before any more.

Thanks a million.

**Comment by lucianopa-msft** [comment]
Awesome!
We are closing this then, thank you for verifying =]
