### ISSUE TITLE
[BUG] App Crashes on Xcode 16

### ISSUE THREAD

**Issue by yasheedv** [Azure/azure-sdk-for-ios#1881]
**Describe the bug**
The application is crashing at launch when running with Xcode 16

***Exception or Stack Trace***

dyld[62802]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: <04AD06A6-6F99-3D10-B524-DF08994AC37F> /Users/yasheed/Library/Developer/CoreSimulator/Devices/66C55B41-9949-4F4B-8D4B-BA1489E973E5/data/Containers/Bundle/Application/43C88B12-E792-439B-97C7-20AC316BA7C0/Smart Office.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling
  Expected in:     <29152051-C3D9-3F37-89DB-FEB770AEF05B> /Users/yasheed/Library/Developer/CoreSimulator/Devices/66C55B41-9949-4F4B-8D4B-BA1489E973E5/data/Containers/Bundle/Application/43C88B12-E792-439B-97C7-20AC316BA7C0/Smart Office.app/Frameworks/AzureCommunicationCommon.framework/AzureCommunicationCommon

**To Reproduce**
Open an existing project with Xcode 16 and run the project in any simulator or device.

**Screenshots**
<img width="1786" alt="Screenshot 2024-09-18 at 1 12 28 PM" src="https://github.com/user-attachments/assets/074d7a53-521e-4ddd-8c25-05761659ee73">

**Setup (please complete the following information):**
 - OS: iOS 18
 - IDE : Xcode 16
 - SDK Version: 'AzureCommunicationCalling', '2.12.0'

**Additional context**
The same SDK is working fine with earlier version of Xcode

**Comment by lucianopa-msft** [comment]
We already have a fix, just need to deliver the new patch version. We will update this thread once fix lands

**Comment by yasheedv** [comment]
Hi @lucianopa-msft, thank you for the swift response. When I can expect the fix? It's a complete development blocker for our team.

**Comment by lucianopa-msft** [comment]
We already have the fix, just sorting out the build and release. Hoping to get it today or tomorrow, no later than Monday.

**Comment by lucianopa-msft** [comment]
Hi @yasheedv, version [2.12.1](https://github.com/Azure/Communication/releases/tag/v2.12.1) is out now with the fix. Can you please verify that it fixes the issue? 
Note that it may take some time for it to be available on CocoaPods.

**Comment by yasheedv** [comment]
@lucianopa-msft the issue got resolved in version [2.12.1](https://github.com/Azure/Communication/releases/tag/v2.12.1). Thank you for the support.

**Comment by JasonWeinzierl** [comment]
@lucianopa-msft Will there be a -beta version released too with the Xcode 16 fixes?

**Comment by lucianopa-msft** [comment]
@JasonWeinzierl Next beta will have it, but I cannot give an ETA on that. I'll will update here as soon as we have it :)

**Comment by lucianopa-msft** [comment]
> @lucianopa-msft Will there be a -beta version released too with the Xcode 16 fixes?

@JasonWeinzierl new beta should be available with fixes https://github.com/Azure/Communication/releases/tag/v2.14.0-beta.1
