### ISSUE TITLE
Create all required documentation

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-ios#190]
The following documentation must be written and have sign-off:

* ```/README.md```
- [ ] Complete
- [ ] Sign-off
* ```/CONTRIBUTING.md```
- [ ] Complete
- [ ] Sign-off
* ```/sdk/core/README.md```
- [ ] Complete
- [ ] Sign-off
* ```/sdk/core/AzureCore/README.md```
- [ ] Complete
- [ ] Sign-off
* ```/sdk/storage/README.md```
- [ ] Complete
- [ ] Sign-off
* ```/sdk/storage/AzureStorageBlob/README.md```
- [ ] Complete
- [ ] Sign-off

**Comment by bsiegel** [comment]
Leaf READMEs are in. Service-level READMEs still remain.

**Comment by tjprescott** [comment]
Closing in favor of individual issues: #372, #373, and #374.
