### ISSUE TITLE
[BUG] azure-sdk-for-ios (main branch) could not be resolved in Swift Package Manager

### ISSUE THREAD

**Issue by albrecht-jun-zhang** [Azure/azure-sdk-for-ios#1906]
**Describe the bug**
In Xcode Swift Package Manager I can't include azure-sdk-for-ios (main branch)

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Open Xcode -> File -> Add Package Dependencies... -> enter azure-sdk-for-ios into search top right -> pick main branch -> click the bottom right Add Package button. You will get the error.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**
![Screenshot 2024-10-07 at 11 52 10 PM](https://github.com/user-attachments/assets/5e12dda2-f21b-4d69-b4f6-00a32e62da86)

**Setup (please complete the following information):**
 - OS: iOS
 - IDE : Xcode, Version 16.0 (16A242d)
 - Version of the Library used: Main branch

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by lucianopa-msft** [comment]
Hey @albrecht-jun-zhang 
That GitHub URL(https://github.com/Azure/azure-sdk-for-ios.git) is not going to work.
In my understanding this repo has a collection of a lot of SDKs but it doesn't support SPM directly. 

So for installing those packages is going to depend on which packages you want to install e.g. if you want AzureCommunicationCommon, use this `"https://github.com/Azure/SwiftPM-AzureCommunicationCommon.git"` as stated in the [Documentation](https://github.com/Azure/azure-sdk-for-ios/tree/main/sdk/communication/AzureCommunicationCommon#swift-cli).

**Comment by tjprescott** [comment]
@lucianopa-msft is correct. This repo is not installable via SPM and there are mirror repos that allow you to install the individual libraries via SPM.

**Comment by albrecht-jun-zhang** [comment]
![Screenshot 2024-10-08 at 7 33 34 PM](https://github.com/user-attachments/assets/64a2976e-35aa-4c52-a4e4-146db9a05143)
Really appreciate that @lucianopa-msft and @tjprescott. My initial intention was to install azure-sdk-for-ios via SPM to import AzureStorageBlob in Swift. But it looks like it's not possible. I will use the Azure Storage REST API directly to upload photos to Azure Blob Storage. Thank you again.
