### ISSUE TITLE
Move AzureCSComputerVision to sdk/computervision

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-ios#191]
Following a conversation on [this PR](https://github.com/Azure/azure-sdk-for-ios/pull/189), we've decided that for consistency we need to move the ```AzureCSComputerVision``` library into the ```sdk/computervision``` folder and regenerate pipelines etc. Additionally the bundle ID would become ```com.azure.computervision```.

**Comment by tjprescott** [comment]
@bsiegel computer vision isn't part of Preview 1. Is there a reason this is included in that milestone?

**Comment by tjprescott** [comment]
Done. This has been removed.
