### ISSUE TITLE
[BUG] call didChangeState does not fire in 2.14.0-beta.1

### ISSUE THREAD

**Issue by JasonWeinzierl** [Azure/azure-sdk-for-ios#1926]
**Describe the bug**

In version `2.14.0-beta.1` of the calling SDK, the event for call state change is not firing for outgoing calls, so we have no way to detect when the call is Ringing/Connected/Disconnected, etc.  The call agent adds and removes the call correctly, and other events seem fine, but the state event itself is not working.

***Exception or Stack Trace***

N/A

**To Reproduce**

1. Set up a `CallDelegate` and assign it to the call when the call is emitted from the call agent.
2. `didChangeState` will not fire when the outgoing call connects or disconnects.

***Code Snippet***

```swift
extension MyCallDelegate: CallDelegate {
  func call(_ call: Call, didChangeState args: PropertyChangedEventArgs) {
    // This never executes.
  }
}
```

**Expected behavior**

`didChangeState` should fire when the call state changes for outgoing calls.

**Screenshots**

N/A

**Setup (please complete the following information):**

 - OS: iOS: 18.0
 - IDE : Xcode 16.0
 - Version of the Library used: AzureCommunicationCalling 2.14.0-beta.1

**Additional context**

This works fine in 2.13.1, but we need to use 2.14.0-beta.1 because it is the only beta version of the SDK that's compatible with Xcode 16 right now.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tjprescott** [comment]
@lucianopa-msft can you please take a look? cc/ @raosanat

**Comment by JasonWeinzierl** [comment]
Updated description to reflect this is only happening for outgoing calls. Incoming calls seem to update state just fine.

**Comment by lucianopa-msft** [comment]
Yes, this is a known issue that has been fixed already. We are just working on an ETA for the release of the next beta in which this issue would be fixed. I will let you know once we have a new beta released.

**Comment by lucianopa-msft** [comment]
@JasonWeinzierl 2.14.0-beta.2 is released with the fix :)
