### ISSUE TITLE
[BUG] Display screen sharing in iOS app

### ISSUE THREAD

**Issue by SarawutSr** [Azure/azure-sdk-for-ios#1943]
**Describe the bug**
I found some differences in the iOS SDK between versions 2.13.x and 2.14.0-beta.2. In version 2.13.x, the screen sharing displayed in the iOS app on a real device is not clear or sharp enough to read the content easily (refer to image-1.jpg).

In contrast, after switching to the latest beta version, 2.14.0-beta.2, the video rendering is noticeably better and sharp enough to make the content readable (refer to image-3.jpg).

The environment is the same for both tests, including the device, code, and network. My internet speed is over 100 Mbps and not shared with anyone.

P.S. Testing on the simulator does not show any difference; both versions look quite good on the simulator.

***Exception or Stack Trace***
No stack trace because it does not have any errors

**To Reproduce**
I tested using two applications.

	1.	The first one, called Admin, uses this sample project:
https://github.com/Azure-Samples/communication-services-web-calling-hero.
	2.	The second is my prototype project, which I customized based on this example:
https://github.com/Azure-Samples/communication-services-ios-quickstarts/tree/main/add-video-calling.

If you would like to test with my test app, please let me know.

**Expected behavior**
The GA version of 2.14.x and later should resolve the issue with unclear video present in 2.13.x.

**Screenshots**
Image-3.jpg: Version 2.14.0-beta.2
Image-1.jpg: Version 2.13.1 (Version 2.13.0 also has this issue)

**Setup (please complete the following information):**
 - OS: iOS 18.1 with iPhone 13 Pro Max
 - IDE : Xcode Version 16.0 (16A242d)
 - Version of the Library used  : [Azure Communication Calling iOS SDK version 2.13.1] and [Azure Communication Calling iOS SDK version 2.14.0-beta.2]
 
In addition, could you provide an update on the GA schedule for version 2.14.x? My team and I are planning to launch our application soon, and we need to resolve this issue first.

![Image](https://github.com/user-attachments/assets/e4f3c10c-ccde-49e1-8277-19b3351f55cd)
![Image](https://github.com/user-attachments/assets/c89a7e3a-e1f3-4144-bd75-bcfab30b3831)

**Comment by lucianopa-msft** [comment]
Hi @SarawutSr 
This is a bug fix indeed made in the SDK now available in 2.14.0-beta.2. See [Changelog](https://github.com/Azure/azure-sdk-for-ios/blob/main/sdk/communication/AzureCommunicationCalling/CHANGELOG.md#bugs-fixed) for more info on which bugs were fixed on 2.14.0-beta.2. 

A bit more info is that this has nothing to do with network or quality of frame received on device, it was an issue on the rendering of those frames.

> P.S. Testing on the simulator does not show any difference; both versions look quite good on the simulator.

Due to some technical limitations, simulator uses a different rendering strategy than real device, that is why we only notice the bug on real devices.

> In addition, could you provide an update on the GA schedule for version 2.14.x? My team and I are planning to launch our application soon, and we need to resolve this issue first.

We are working on next GA release, but cannot provide a specific ETA. Hopefully in the next couple of weeks we should have either a release or be close to at least.

**Comment by lucianopa-msft** [comment]
I am closing this since bug is actually fixed. But I will let you know once 2.14.0 GA is out :)

**Comment by SarawutSr** [comment]
> I am closing this since bug is actually fixed. But I will let you know once 2.14.0 GA is out :)

I just found out from your link that it will be fixed in the next release. Next time, I’ll check the information from your link first.

Thanks a million. ;)

**Comment by SarawutSr** [comment]
> [@SarawutSr](https://github.com/SarawutSr) 2.14.0 GA is released!

Thank you :)
