### ISSUE TITLE
Noise cancellation

### ISSUE THREAD

**Issue by BigVeila** [Azure/azure-sdk-for-ios#1956]
I wonder if the iOS SDK supports a noise reduction feature. Currently, I am using the STT feature, and the Azure is recognize other sounds (5 meters from the mic).

**Comment by tjprescott** [comment]
@lucianopa-msft could you weigh in?

**Comment by lucianopa-msft** [comment]
Hey @BigVeila,
We do have a support for noise suppression in our calling SDK, you can refer to [Add audio quality enhancements to your audio calling experience](https://learn.microsoft.com/en-us/azure/communication-services/tutorials/audio-quality-enhancements/add-noise-supression?pivots=platform-ios#before-the-call-starts) where you can apply a levels of noise suppression through audio options in a call. 
Example: 
```swift
let outgoingAudioOptions = OutgoingAudioOptions()
let filters = OutgoingAudioFilters()
filters.noiseSuppressionMode = NoiseSuppressionMode.high
outgoingAudioOptions.audioFilters = filters
```
And apply to call options :)

**Comment by BigVeila** [comment]
@lucianopa-msft It seems like what you’re referring to is for calls. Currently, I’m only using Speech To Text, and I can not apply for SPXPushAudioStream,... From what I researched, there is a feature called Microsoft Audio Stack (MAS), but it only supports C# and Java.

**Comment by lucianopa-msft** [comment]
Oh so you are not using AzureCommunicationCalling SDK, you just want speech to text in any Azure SDK? It is that the question?
Can you elaborate more on your scenario which Azure SDK are you using, which version and how are you getting STT feature?

**Comment by BigVeila** [comment]
Yes, I am using Azure’s Speech-to-Text (STT) feature for my language learning application. Currently, I am using Azure version 1.40.0 (pod MicrosoftCognitiveServicesSpeech-iOS). I want to apply noise reduction because I am testing in an office environment, and the application is intended for working users. At a distance of 5 meters from the microphone, unwanted sounds are still mixed in. I have researched using SPXPushAudioStream but have not found a solution.

**Comment by lucianopa-msft** [comment]
This doesn't look like a AzureCommunicationCalling SDK issue, so should it be transferred to some other Azure SDK?
cc @tjprescott

**Comment by tjprescott** [comment]
Closing as this is not a supported feature of the SDK.
