### ISSUE TITLE
Willow framework crash

### ISSUE THREAD

**Issue by serddmit** [Azure/azure-sdk-for-ios#207]
### Environment

- iOS version: 13
- Xcode version: 11.3
- Azure.iOS SDK:
- Azure.iOS SDK version: 0.5.0
- CocoaPods or Carthage: Carthage

### Bug Summary
When add a dependency using Carthage, my app crashes with an exception "Willow: no matching architecture in universal wrapper"

Willow framework has only armv7 arm64, that couldn't be used for simulator.

### Code snippet

```swift
// TODO: add code here (if applicable)
```

**Comment by bsiegel** [comment]
Closing this issue - it seems it's most likely to be an issue with the Willow framework itself, so I would try updating that dependency. If it is in fact an issue with our library, unfortunately we aren't planning any further changes to the Track 1 SDK.
