### ISSUE TITLE
Internal public API review for Preview 1

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#210]
- [x] Review the public API and hide any members that are not intended to be part of the customer-facing API.
<del> Submit public API (.swiftinterface) for architect review</del>
<del> Make adjustments and pass architect review </del>
**Moved to issue #322**

**Comment by tjprescott** [comment]
Moved the arch-board review to separate issue #322 so as not to block Preview 1, per @mayurid.
