### ISSUE TITLE
Complete a UX study of the Preview 1 SDK libraries

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#213]
- [x] Document Preview 1 champion scenarios
- [x] Document hypotheses for Preview 1 APIs
- [x] Construct sample applications to test champion scenarios and hypotheses
- [x] Write script(s) for UX study
- [x] Complete UX study

UX study results will be incorporated in a future preview.

**Comment by tjprescott** [comment]
This done. :)
