### ISSUE TITLE
Package resolution failed: "Azure.iOS" could not be resolved

### ISSUE THREAD

**Issue by ricardopereira** [Azure/azure-sdk-for-ios#218]
### Environment

- iOS version: iOS 13
- Xcode version: Xcode 11.4
- Azure.iOS SDK: yes
- Azure.iOS SDK version: 0.5
- CocoaPods or Carthage: SPM 😉 

### Bug Summary

Couldn't add Azure.iOS as dependency using Swift Package Manager:

```
Package resolution failed: "Azure.iOS" could not be resolved
/Volumes/Extra/Library/Xcode/DerivedData/shieldme-gkmfdiommlczgcdrkbvncigufsxz/SourcePackages/checkouts/Azure.iOS/Package.swift: target at '/Volumes/Extra/Library/Xcode/DerivedData/shieldme-gkmfdiommlczgcdrkbvncigufsxz/SourcePackages/checkouts/Azure.iOS/AzureCore' contains mixed language source files; feature not supported
```

### Steps to Reproduce

Just try to integrate `https://github.com/azure/Azure.iOS` using Xcode:  "Swift Packages" > "Add Package Dependency...".

### Expected Behavior

Successful integration, since there's a `Package.swift` file in the repository.

### Actual Behavior

![Screenshot 2020-02-24 at 11 29 26](https://user-images.githubusercontent.com/3541185/75149394-c0389300-56f9-11ea-8cf1-cf7f3c03f30f.png)

**Comment by tjprescott** [comment]
The legacy AzureCore is not supported by Swift Package Manager. We are working on a new version of AzureCore which should support SPM.
