### ISSUE TITLE
Release process for Swift Package Manager

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-ios#222]
Implement support for Swift Package Manager. There should be a single ```Package.swift``` file in the repo which includes the entirety of the SDK. During the release process there should be a job which tags the repository at the appropriate commit sha so that Swift PM can locate the version of the package it needs.

**Comment by bsiegel** [comment]
@mitchdenny Was there anything else we needed to do on this item? Perhaps add / update READMEs to cover the release process? IIRC, the SwiftPM process we landed on was working as expected, the only thing left was to automate the release tagging process.

**Comment by mitchdenny** [comment]
Yep. Still need to automate that. One of the things that I've been pondering is the best way to track the version number. Unlike our binary composed language/runtimes, the version number is usually baked into the sources. Whereas in Swift PM its really just a commit sha (directly) or a tag (indirect point to commit sha).

One option is not storing it in the repo at all and instead allowing a release pipeline to specify a variable with the version number which then just tags the repo.

Alternatively we could put a file (```eng/version.txt```) in the repo which contains the version to be released and that would be picked up and used by the pipeline and for any other automation fairly easily (just pipe the file into a variable). It also means that the version number to be published is something that is reviewed via PR process rather than an arbitrary decision that someone makes when they kick off the pipeline for release.

Finally, I'm assuming we are going to need README.md and CHANGELOG.md files in the repo. I think we need to decide at what level we are going to do that for the iOS repository. In other repos we have a CHANGELOG and README per module, but in other repos they also ship independently. Perhaps in iOS we just have one README.md and one CHANGELOG.md in the root of the repo since that is the shippable unit.

If we did that then I would be inclined to lift the tag from the most recent entry in the changelog, effectively forcing a changelog entry to be updated prior to a release working ;)

**Comment by bsiegel** [comment]
We have one README per module, and one at the top-level. I think that makes sense since each library has its own long-form documentation. I would be fine having a single top-level CHANGELOG if the entire repo is versioned together. We should break down per-library changes in subheadings under each revision in the changelog. I would be fine using the changelog as the source of truth for the version. The process would then be to cut a release which tags the current HEAD commit, and then commit a new changelog entry with the next version number heading and the message "Unreleased" or some other placeholder text.

**Comment by mitchdenny** [comment]
Closing as it is duplicated with #532

**Comment by mitchdenny** [comment]
(commentary around README and CHANGELOG is useful though)
