### ISSUE TITLE
MD5 hashing enabled yields EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#248]
Workaround was to turn this feature off temporarily.

**Comment by bsiegel** [comment]
As of #267, tests for all hashing methods are passing. Was the crash happening in the hash() method itself, or was it happening somewhere else in the client code?

**Comment by tjprescott** [comment]
I don't recall, but feel free to go to the TODO, change the value to true and see what happens. It wasn't that the hash didn't match--it was that there was a bad access error.
