### ISSUE TITLE
LocalURLs created from URLs provided by the OS can't be persisted

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#269]
If the developer receives a URL for a file from the OS (e.g. received in the UIImagePickerControllerDelegate method), the only way to turn that into a `LocalURL` is by calling `init(fromAbsoluteUrl:)` which does no processing on the provided URL. Since the URL will be scoped to the application container, next time the app runs, the URL will be invalid.

**Comment by tjprescott** [comment]
@bsiegel does this need to be addressed for preview 1?
