### ISSUE TITLE
Add SwiftUI example project

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#309]
We have a sample project for traditional UIKit development using storyboards. We should have a SwiftUI-based example project for those who prefer that approach.

**Comment by osca2000** [comment]
No update yet?

**Comment by tjprescott** [comment]
@osca2000 at the moment we are focused on readying and releasing our AzureCore library for preview, so no update on this right now.

**Comment by tjprescott** [comment]
This was completed with #675.
