### ISSUE TITLE
UX Study Discussion #1: Accessing Raw Response during calls

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#310]
The callback parameters from client operations is generally `Result<X, Error>, HttpResponse` so that the developer can inspect the raw HTTP response if desired, or ignore it (with _) if not needed. This is to support the guidelines that saw the default return value should be the deserialized Foo, but that some way to access the raw HTTP response should be provided. Alternatives were suggested during development to the approach we took, and we should revisit those and novel approaches.

**Comment by tjprescott** [comment]
Per discussion on 6/24, we agreed to time box a prototype where the `AzureTask` object has a `lastResponse` property containing the last HTTP response object. Also, we need to ensure that response is accessible for paged operations and up/download operations.

**Comment by tjprescott** [comment]
After investigation, I was able to get to this level of simplification:

From
```Swift 
let task = blobClient.listBlobs(inContainer: ..., withOptions: ...) { result, httpResponse in
  print(httpResponse)
```

To
```Swift 
let task = blobClient.listBlobs(inContainer: ..., withOptions: ...) { result in
  print(task.lastResponse)
```

However, here Swift complains that `lastResponse` is being used within its own initial value and thus won't compile. Thus, unless we want to try and stuff the HTTP response somewhere in the Result (which I wouldn't recommend) there's not a simple way of getting the response object out of the callback signature. 

My 2 cents... I don't think most people will care or feel that put-upon by using the `_` so I would recommend closing this issue until and unless preview 1 shows a lot of feedback on this.

**Comment by bsiegel** [comment]
Interesting - can you push up that as a branch somewhere, I'm curious to see what's going on. That said, if that's the case then I'm 👍 to closing this issue.

**Comment by tjprescott** [comment]
@bsiegel the branch is called RawResponseExperiment.

**Comment by bsiegel** [comment]
Thanks, I took a look and I think I see why the compiler is doing this. I suspect that it's correct in this instance, so I'm good with just closing this issue for now.
