### ISSUE TITLE
Refactor PagedCollection to match the guideline requirements / API

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#326]
This is a fairly significant refactor, so we should do this as a separate PR rather than lumping it in with the other small API changes needed to match the guidelines.

**Comment by tjprescott** [comment]
Needs:
- [ ] `pagedCollection.forEachPage`
- [ ] `pagedCollection.forEachItem`
- [ ] `pagedCollection.syncCollection`
