### ISSUE TITLE
Transfer Manager should support background transfers

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#332]
- [ ] Define how TransferManager will interface with the OS to run transfers in the background

**Comment by maniacs-engineerica** [comment]
Do you have a deadline for this improvement? Uploading in background is not working and we are really interested on it.

**Comment by tjprescott** [comment]
Hi @maniacs-engineerica, there is no ETA for resolution on this issue. The Storage Swift library is not being actively developed at this time and has not been formally released, even as a preview.
