### ISSUE TITLE
Ensure SwiftPM model will work with multiple targets / multiple versions

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#340]
We need to make sure that our plan for using SwiftPM will work if the customer wants to include multiple targets, rather than importing the entire SDK as a single dependency. The customer should be able to import one or multiple targets from our SDK as separate pieces.

We also need to make sure that since the entire SDK has to be versioned together, a customer should be able to pull in target A from our SDK at version X, and target B from our SDK at version Y, assuming that B@Y has either no dependency on A at all, or has a dependency on A@>=X.

**Comment by mitchdenny** [comment]
I was looking at the XCode UX, I couldn't see where it allows you to specify a target. Even if we don't specify a target, what is the primary concern here, adding build time for the entire SDK to their build time? Regarding target to target compat, I think that is a pipe dream. If it is one package, it is one package.

**Comment by bsiegel** [comment]
The UX allows you to select one or more products to add as dependencies, unselected products won't be built & linked into your project. This feels like a pretty good UX to me.

![Screen Shot 2020-07-08 at 6 06 12 PM](https://user-images.githubusercontent.com/96068/86990085-a8195b80-c150-11ea-92ed-891e9d43507a.png)

**Comment by mitchdenny** [comment]
Agreed. And it appears like it works correctly with external dependencies as well. I'm going to close this since I think this as more of an investigation than an outcome. But I'm happy with where we have landed on all this.
