### ISSUE TITLE
Add RetryPolicy

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#356]
Add a FixedDelay and an ExponentialBackoff RetryStrategy. Add a RetryPolicy that implements a provided RetryStratgey. Based on the provided TransportOptions, configure the RetryPolicy to use the provided RetryStrategy. Basically, try to match how this works in Android.

**Comment by bsiegel** [comment]
Relates to #145

**Comment by tjprescott** [comment]
@adrianhall any thoughts here? I thought we had discussed retry policies early on during the guidelines drafting and it was decided that retry policies were N/A for mobile?
