### ISSUE TITLE
AzureData .Query() initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by tmonroyso** [Azure/azure-sdk-for-ios#364]
**Query/Question**
I Downloaded and compiled azure-sdk-for-ios-0.5-2.0 AzureData Framwork. When I tried to use the Query function I had the following error:  initializer is inaccessible due to 'internal' protection level. What I did is to open the Query.swift file and change the init() { } to public and now it works. I am posting this here because I wasn't sure if that was a bug. 
***Why is this not a Bug or a feature Request?***
Might be a bug. 

**Setup (please complete the following information if applicable):**
 - OS: [iOS]
 - IDE : [Xcode 11]
 - Version of the Library used:   azure-sdk-for-ios-0.5-2.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by tjprescott** [comment]
@tmonroyso that certainly sounds like a bug. If you want to submit a PR to fix it we would gladly accept it, but the Track 1 preview libraries are no longer being actively maintained.

**Comment by tmonroyso** [comment]
Thanks for your comment, sure I can submit a PR. So are there any more recent libraries to try/use?

**Comment by tjprescott** [comment]
Hi @tmonroyso not to my knowledge. This was a preview SDK done by a Microsoft employee as a side project. If you find the code is useful I would encourage you to the fork the repo and continue to use it. Our current team is working on new Azure SDKs, but I don't know when or if the legacy AzureData might fall into our charter.

**Comment by tmonroyso** [comment]
Oh I see, perfect! thanks for your comments and feedback. I will do so.

**Comment by bsiegel** [comment]
Closing this issue as it appears to be inactive. If there are further issues with the Track 1 SDK, please file an issue and we'll make a best effort to assist you.
