### ISSUE TITLE
Embedded CoreData data model does not work with Swift Packages (tools version 5.2)

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-ios#367]
As part of the validation of the Swift Package for the Azure SDK I discovered that the embedded CoreData data-model that AzureStorageBlob depends on is not being brought across into applications when the Swift Package is installed. This is because that the Swift Package format supported by Swift tools 5.2 and Xcode 11 does not support resource embedding. This is a new feature associated with Swift tools 5.3 and Xcode 12.

We need to find a work around for this (possibly imperatively creating the data model from within our code rather than relying on the embedded definition). We'll need to do this until we can adopt the 5.3 toolchain/Xcode 12 some time this year.

Depending on timeframes we could perhaps jump straight to 5.3/Xcode 12 since we know we are going to want it soon for MSAL (which will likely ship as a binary framework via Swift Package).

**Comment by bsiegel** [comment]
Since this toolchain is out, let's investigate whether this "just works" with 5.3. If so we can close the issue.
