### ISSUE TITLE
Make AzureError ObjC compatible

### ISSUE THREAD

**Issue by thdinizm** [Azure/azure-sdk-for-ios#411]
**Is your feature request related to a problem? Please describe.**
AzureError is not ObjC compatible.

**Describe the solution you'd like**
If AzureError was ObjC compatible, we could use it in our Communication package, keeping it consistent with the rest of the codebase.

**Describe alternatives you've considered**
Right now we're using the Error base class instead.

**Additional context**
It is a requirement for the Communication package to support ObjC for our internal ObjC libraries.

**Comment by bsiegel** [comment]
This is going to have to be addressed as part of a larger effort to bridge our Swift-based Core library with ObjectiveC-based client libraries. Closing this issue but we will cover it as part of this much larger effort.
