### ISSUE TITLE
Create Auto Release Notes Script

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-ios#439]
Take this .NET script that Pavel created and adapt it to iOS

https://github.com/Azure/azure-sdk-for-net/blob/master/eng/scripts/Collect-Changelogs.ps1

**Comment by mitchdenny** [comment]
Taking this for now. It might end up coming back :)

**Comment by weshaggard** [comment]
Tracking the general work with https://github.com/azure/azure-sdk/issues/1694
