### ISSUE TITLE
Storage API is unreleased

### ISSUE THREAD

**Issue by rnikander** [Azure/azure-sdk-for-ios#469]
The documentation for the storage API says to download the latest release and extract the .framework files: 

https://github.com/Azure/azure-sdk-for-ios/tree/master/sdk/storage/AzureStorageBlob 

But, the latest release (1.0.0-beta) doesn't seem to have those files.

https://github.com/Azure/azure-sdk-for-ios/releases

**Comment by bsiegel** [comment]
Hi @rnikander, The AzureStorageBlob library is still in active development and we haven't yet published a release. The installation instructions will be updated before we publish our first release, but for now there is no release version you can consume.

If you'd like to give it a try (in its development state, of course), you can clone the Git repository and import the AzureCore and AzureStorageBlob libraries. Keep in mind, this code is still in a very early state and should not be used for production applications.

**Comment by tjprescott** [comment]
Since this is likely to be a common refrain until storage is released I have pinned this issue.

**Comment by tjprescott** [comment]
Storage is not released in any preview form.

**Comment by tjprescott** [comment]
For folks needing Storage, this Objective-C-based library from the Storage team is probably your best bet:
https://github.com/Azure/azure-storage-ios

**Comment by elemental21** [comment]
We need Storage and tried using https://github.com/Azure/azure-storage-ios as suggested. 

Our first attempt at building ended up with this error. 
![image](https://user-images.githubusercontent.com/7585464/182721973-6ef9b093-8201-47be-af9e-c555ab25e2cb.png)

Based on that error we found suggestions to build the framework manually
![image](https://user-images.githubusercontent.com/7585464/182719501-f12275a3-bdd6-432c-931a-4821109e87de.png)

We ended up with "legacy build system" error that causes the build to fail
![image](https://user-images.githubusercontent.com/7585464/182719312-b64f465f-645b-4ac0-bd7d-d0d336a69113.png)
![image](https://user-images.githubusercontent.com/7585464/182719339-0bb12b00-92f3-4f9d-9bff-91ccfc152dfe.png)

Any suggestions on how to get this working?

**Comment by tjprescott** [comment]
You would need to engage the maintainers in the https://github.com/Azure/azure-storage-ios repo.

**Comment by tjprescott** [comment]
Closing this issue as PR #1336 removed the experimental storage code from the `main` branch.
