### ISSUE TITLE
[QUERY] http://www.github.com/

### ISSUE THREAD

**Issue by Ryanyellowhair** [Azure/azure-sdk-for-ios#483]
**Query/Question**
A clear and concise ask/query.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by tjprescott** [comment]
Closing as I don't see any information in this issue, just the template boilerplate.
