### ISSUE TITLE
Helper Structure for QueryParams

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#514]
We can simplify Autorest.Swift codegen if the syntax for a required query param and an optional one work the same way. If an optional param evaluates to nil, it should be ignored and not added to the query params.

**current**
```swift
func test(var1: String, var2: String?) {
  var queryParams: [QueryParameter] = [
   ("var1": var1)
  ]
}
if let value = var2 {
  queryParams.append(("var2": value))
}
```

**desired**
```swift
func test(var1: String, var2: String?) {
  var queryParams = QueryParameters([
   ("var1": var1),
   ("var2": var2) // ignored if value is nil
  ])
}
```

cc/ @sacheu

**Comment by sacheu** [comment]
For this desired case, 
```
func test(var1: String, var2: String?) {
  var queryParams = QueryParameters([
   ("var1": var1),
   ("var2": var2) // ignored if value is nil
  ])
}
```
We need to support these cases:
1. when var2 is optional, AzureCore needs to unwrap the optional value.
2. when var2 is an enum, AzureCore needs to use `enumQuery.rawValue`
3. when var2 is data, AzureCore needs to convert that to String `String(bytes: byteQuery, encoding: .utf8)  ` before add to query param
4. when var2 is a string array, AzureCore needs to convert to a String using ',' as separator `arrayQuery.map { String($0) }.joined(separator: ","))`
5. when var2 is int or bool,  AzureCore needs to convert to a String using `String(anInt)`, `String(aBool)`
6  when var2 is Date,  AzureCore needs to convert to String using ` let dateQueryString = DateFormatter().string(from: dateQuery)     `

**Comment by sacheu** [comment]
7. AzureCore also need to support when var2 is an array of optional elements, e.g. `[String?]` see https://github.com/Azure/autorest.python/blob/autorestv3/test/vanilla/AcceptanceTests/test_url.py 

```
def test_array_query():
    return ["ArrayQuery1", r"begin!*'();:@ &=+$,/?#[]end", None, ""]
```
