### ISSUE TITLE
[BUG] `swift build` broken on master branch

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#570]
The following PR:
https://github.com/Azure/azure-sdk-for-ios/pull/503

has broken the ability to run `swift build` of any Targets (not just AzureCommunciation). 

We should:
1) Resolve the error (or revert the PR)
2) Add a test to CI to ensure that `swift build` always passes.

**Comment by bsiegel** [comment]
I suspect the right thing to do here is probably to add a filter on the test targets in the Package.swift file, so that the targets only include *.swift files. That's where I'd start at least.

**Comment by JoshuaLai** [comment]
Package.swift should be able to support excluding files with an exclude[]. So I am going to try to exclude the obj-c tests but if there is a super high urgency I created the PR to revert the change just in case here: https://github.com/Azure/azure-sdk-for-ios/pull/571
