### ISSUE TITLE
Support for live testing in iOS repository

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#584]
We need to add support for live testing into the iOS repository. We should follow the same pattern that we use for the other repositories, that is having a ```tests.yml``` file per service directory and a ```test-resources.json``` file. We then need to figure out how we invoke the tests in such a way that the environment information that live tests normally get access to can work within the emulator (if that is an issue).

Elements of this work being completed:

1. The addition of a test archetype template
2. Tests YAML files for existing service directories.
3. Pipeline generation automatically creating live test pipelines.
4. What matrix do we need to support?

**Comment by tjprescott** [comment]
Adding to the AzureTest framework Epic, as this issue will certainly leverage it.

**Comment by tjprescott** [comment]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/48/Create-a-new-Live-Test-pipeline

**Comment by tjprescott** [comment]
This isn't done. @benbp's PR was boilerplate, but configuration is still needed to actually get the pipeline up and running.

**Comment by benbp** [comment]
My mistake, I told Scott to close it but forgot the full context in the moment.

**Comment by benbp** [comment]
@tjprescott should we change who this is assigned to? I'm happy to help get things further set up using the boilerplate, but I think the rest of the work is on the iOS side?
