### ISSUE TITLE
[BUG] StorageSharedKeyCredential stringToSign function

### ISSUE THREAD

**Issue by RichardGrundy** [Azure/azure-sdk-for-ios#585]
When using StorageSharedKeyCredential the stringToSign function produces an incorrect output when the contentLength header is not set. This occurs during blob file upload, but only on the commit request after putting the file data. The commit request is actually 176 bytes long but has no header set which means the current code sets the contentLength line to an empty string.

**To Reproduce**
upload files to blobstorage container using shared key credentials

***Code Snippet***
from the StorageSharedKeyCredential class

```
internal func stringToSign(forRequest request: HTTPRequest) throws -> String {
        let headers = request.headers
        var stringToSign = request.httpMethod.rawValue + "\n"
        stringToSign += (headers[.contentEncoding] ?? "") + "\n"
        stringToSign += (headers[.contentLanguage] ?? "") + "\n"

        // This will need to change to support API version 2014-02-14 and earlier.
        stringToSign += (headers[.contentLength] == "0" ? "" : (headers[.contentLength] ?? "")) + "\n"

        let requestLength = request.data?.count ?? 0
        stringToSign += (headers[.contentLength] ?? "\(requestLength)") + "\n"

        stringToSign += (headers[.contentMD5] ?? "") + "\n"
        stringToSign += (headers[.contentType] ?? "") + "\n"
        stringToSign += (headers[.xmsDate] != nil ? "" : (headers[.date] ?? String(describing: Date(), format: .rfc1123))) + "\n"
        stringToSign += (headers[.ifModifiedSince] ?? "") + "\n"
        stringToSign += (headers[.ifMatch] ?? "") + "\n"
        stringToSign += (headers[.ifNoneMatch] ?? "") + "\n"
        stringToSign += (headers[.ifUnmodifiedSince] ?? "") + "\n"
        stringToSign += (headers[.range] ?? "") + "\n"

        stringToSign += canonicalized(headers: headers)
        stringToSign += try canonicalized(resource: request.url)
        return stringToSign
    }

```

**Expected behavior**
The string should have the content length in even if the contentLength header has not been set. 

My fix is to replace
        stringToSign += (headers[.contentLength] == "0" ? "" : (headers[.contentLength] ?? "")) + "\n"

with
        let requestLength = request.data?.count ?? 0
        stringToSign += (headers[.contentLength] ?? "\(requestLength)") + "\n"

**Setup (please complete the following information):**
 - OS: MacOS Big Sur
 - IDE : XCode
 - Version of the Library used: 1.0.0-beta-6

**Comment by RichardGrundy** [comment]
Happy to submit a pull request with this suggested change if agreed

**Comment by tjprescott** [comment]
@RichardGrundy thank you for the report! Feel free to open a PR and tag @bsiegel as reviewer.

**Comment by RichardGrundy** [comment]
Thanks will do, I'm investigating where the issue originates as I think the header for content length is being set in each of the previous requests just not the commit request. Will have a PR shortly.
