### ISSUE TITLE
Update swift toolchain to 5.3

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#597]
5.3 brings support for binary framework packages (needed to ship e.g. Communication-Calling as a swift package), as well as embedded resources support (needed to support CoreData model files, which so far are only used in Storage-Blob).

Related: #367

**Comment by tjprescott** [comment]
Generally, we should use the lowest version of SwiftTools possible, as it determines the minimum Swift version necessary to compile.
