### ISSUE TITLE
[BUG] AzureCommunicationChat unit tests don't execute in CI unit test stage 

### ISSUE THREAD

**Issue by Leoaqr** [Azure/azure-sdk-for-ios#609]
**Describe the bug**
I added unit tests for AzureCommunication chat service, and add unit tests into "all" schema. After that, I build and run it locally, and I can see my newly added unit tests appears in the result. However, when I trigger the pipeline, I don't see my new unit tests being executed in the unit test stage.

***Exception or Stack Trace***
N/A

**To Reproduce**
Commit anything and trigger CI to run unit tests

***Code Snippet***
N/A

**Expected behavior**
Expected unit tests being executed.

**Screenshots**
"all" schema setup
![image](https://user-images.githubusercontent.com/10414034/102552686-751bb200-4076-11eb-8167-6d26ebc70207.png)

![image](https://user-images.githubusercontent.com/10414034/102552723-81a00a80-4076-11eb-844e-2a131c79f0fa.png)

Local unit tests passed
![image](https://user-images.githubusercontent.com/10414034/102553029-08ed7e00-4077-11eb-893e-319c9cc31e26.png)

However, it doesn't appear in the cloud build log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=659474&view=ms.vss-test-web.build-test-results-tab

**Setup (please complete the following information):**
 - OS: OS X 10.15.7
 - IDE : Xcode Version 12.2 
 - Version of the Library used

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tjprescott** [comment]
Fixed in PR #610.
