### ISSUE TITLE
Communication Token tests failing on CI

### ISSUE THREAD

**Issue by knvsl** [Azure/azure-sdk-for-ios#662]
**Describe the bug**

- There are communication token tests in the **feature/AzureCommunication** branch that are failing in CI. 
- They consistently pass locally, the issue only seems to be happening on CI.
- These tests are **only on the feature branch so it hasn't been affecting PRs to master,** but we are planning to merge the feature branch to master soon so creating the issue as a reminder to investigate this.

Some of the offenders I've noticed, but it seems to vary:
testCreateStaticToken()
testCreateRefreshableWithInitialToken()
test_RefreshTokenProactively_TokenAlreadyExpired()
test_RefreshTokenProactively_FetchTokenReturnsError()

**To Reproduce**
Run Communication tests locally, watch them pass. 
Run tests on CI (open PR into feature/AzureCommunication), watch tests fail, re-run and watch them pass after some arbitrary number of attempts.

**Comment by JoshuaLai** [comment]
`xcodebuild -workspace AzureSDK.xcworkspace -scheme all -destination "platform=iOS Simulator,OS=14.3,name=iPhone 12 Pro Max" -configuration Debug test ` command line script

**Comment by tjprescott** [comment]
@JoshuaLai  @knvsl has then been resolved or are these tests disabled?

**Comment by JoshuaLai** [comment]
@tjprescott the objc tests have been reenabled just right after beta 8 release. Just keeping an eye on things in the CI. There still might be some instability in the token tests.

**Comment by tjprescott** [comment]
I'll close for now and we can reopen if the issue reappears.
