### ISSUE TITLE
Need an identifier in `CommunicationIdentifier`

### ISSUE THREAD

**Issue by terrychen1122** [Azure/azure-sdk-for-ios#674]
In the latest version of AzureCommunication, `CommunicationIdentifier` is an empty protocol where a few different types of Identifiers implement it. As a client of the Azure calling SDK, we get the identity (which is a `CommunicationIdentifier`) of each participant. 

In order to maintain the states of each participant, we will need an identifier to uniquely identify each participant. We currently cast it to `CommunicationUserIdentifier` because the current use case is limited to this type. However, this is not extensible and also error-prone in the long run. Can we have an id/identifier field in this protocol? My assumption is each type of user has an id. Even in various formats, but it will still uniquely identify the user.

For instance, now each type has one id (although they are named differently):
CallingApplicationIdentifier -> identifier
CommunicationUserIdentifier -> identifier
MicrosoftTeamsUserIdentifier -> userId
PhoneNumberIdentifier -> phoneNumber
UnknownIdentifier -> identifier

A code snippet in our application:
```
// This is a snippet of the category/extension implementation of ACSRemoteParticipant in our codebase
- (NSString *)identifier {
    CommunicationUserIdentifier *userIdentifier = LIN_CAST_OR_NIL(self.identity, CommunicationUserIdentifier);
    if (userIdentifier) {
        return userIdentifier.identifier;
    }
    LILOGA(@"Invalid user identity is found");
    return @"UNKNOWN";
}
```

**Comment by RezaJooyandeh** [comment]
Thank you @terrychen1122 for reaching out. 

 > My assumption is each type of user has an id. Even in various formats, but it will still uniquely identify the user.

You are correct. But we intentionally did not expose the internal id as it would make it harder for developers to create them. The internal id has a complex schema, hence we do not want to expose them. That is why we recommend to use the reference to the object as the identifier (or key in your mapping) instead of converting it to a string.

**Comment by tjprescott** [comment]
@RezaJooyandeh is this issue resolved?

**Comment by RezaJooyandeh** [comment]
Yes, it should be.
