### ISSUE TITLE
iOS Azure Pipeline Enhancements

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#681]
Other language SDKs (including Android) have the ability to queue a manually build from the Azure Pipelines tab and run their release process through that. We should have the same for iOS. 

- What tests we have should be reported for the Ship Ready dashboard. As I understand, this requires a certain configuration in the Azure Pipelines.
- The release pipeline should follow the build pipeline, and should include the following steps, similar to other languages (Android, Java, Python):
  - Create release tag
  - Publish CocoaPods to Trunk
  - Publish jazzy docs
  - Update package version

What we have:

![image](https://user-images.githubusercontent.com/5723682/106947089-cc391d00-66de-11eb-9897-6e86de0aace1.png)

What we want:

![image](https://user-images.githubusercontent.com/5723682/106947185-ed9a0900-66de-11eb-9ae3-97c8a87522d2.png)

**Comment by mitchdenny** [comment]
@benbp this is mostly done, except for docs which still needs some work, but I think it is worth collaborating with @danieljurek on this space given we want docs to flow through the normal pipeline ultimately.

**Comment by tjprescott** [comment]
Revisiting this, I would say the only item left is the jazzy docs. We bump the version manually prior to release so I'm not sure there's much value in a post-release automated bump.
