### ISSUE TITLE
AzureCommunicationChat: Guidelines Exceptions

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#787]
- [ ] Trouter bitcode enabled. [Trouter]
- [ ] Trouter to support $ARCH_STANDARD (arm64) [Trouter]

**Comment by kevalvadoliya** [comment]
Hello @tjprescott, Any update on this? I am not able to release the TestFlight build. 
Could you please let me know another way to release TestFlight build for arm64 architecture?

**Comment by tjprescott** [comment]
@knvsl do you have an update on this or know who the right dev would be on the ACS Chat team?

**Comment by juancamilor** [comment]
@tjprescott due to other priorities we had to put this one on hold. We will be looking at closing all the iOS pending tasks on Q1 2022. 
FYI @glorialimicrosoft  @LuChen-Microsoft

**Comment by kevalvadoliya** [comment]
Hello @tjprescott, Any update on this?

**Comment by tjprescott** [comment]
Hi @kevalvadoliya, @juancamilor is your best point of contact for this issue, but my understanding is that one of the internal dependencies is not arm64 compatible and thus Chat cannot be either. @juancamilor can you comment further?

**Comment by conrad030** [comment]
I'm facing the same issue. I'm not able to build the project when AzureCommunicationChat is embeded via Cocoapods, even if Bitcodes are disabled. Is there any workaround for now?
