### ISSUE TITLE
Refactor AzureDataTests

### ISSUE THREAD

**Issue by ftchirou** [Azure/azure-sdk-for-ios#79]
Refactor `AzureDataTests` following the model of [_AzureDataTests](https://github.com/Azure/Azure.iOS/blob/master/AzureData/Tests/_AzureDataTests.swift).

The main difference is that each test case will be responsible of ensuring that a resource exists by calling one of the `ensure...Exists` functions at the beginning of the test case. As opposed to having a global `ensureDatabase = true` set for all the test cases in the `setup()` function.

**Comment by bsiegel** [comment]
Closing as wontfix, we are preparing for a release of the Track 2 SDK libraries which are based on a different codebase.
