### ISSUE TITLE
Chat Record/Playback Enhancements

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#882]
- The test setup should construct a resource group and the resources needed to support the test (in this case, an ACS resource, a couple users, and a token). Currently that must be done manually using a script. The test should automatically delete that resource group when the test completes. Complicating this is the fact that there is no management plane SDK for iOS. See issue #892.
- The scrubbing mechanism needs to be more robust.
- The need to manually register stubs is problematic and results in a lot of boilerplate code. Ideally, all of that metadata like status code, path, etc should be contained in the recording, and all of that can be registered by simply processing the recordings.

**Comment by knvsl** [comment]
Covered most of it above, just following up notes from the meeting:
- We need to keep the ability to scrub out sensitive data from the recorded responses
- Ideally we remove the boilerplate code - registering stubs & also recording responses, so devs writing tests don't have to think about it
- Avoid conflicts between tests, ie GET message vs GET message on some updated message - same call but different tests might want different responses, avoid conflict between unit test mocks and live test recordings

**Comment by tjprescott** [comment]
With the recent merging of AzureTest, these broad goals have been achieved. We can create specific issues for follow-on work.
