### ISSUE TITLE
[BUG] chatThreadClient.listMessages option doesn't work

### ISSUE THREAD

**Issue by sangkuOH** [Azure/azure-sdk-for-ios#954]
When I try pagination to get past chat history, 
to this i use ListChatMessagesOptions() as you see in README,
but I just input the startTime parameter in the instance 
Data from that time to the present can be communicated.
If my understanding is correct, it seems that it is normal to communicate data recorded in the past from the time entered in startTime. as much maxpagesize
Am I wrong? Or is it a bug?
it iOS 14.0 Xcode  12.5

**Comment by knvsl** [comment]
Yes you're understanding sounds correct, for ListChatMessagesOptions we expose startTime and maxPageSize. 

`startTime` works as you described above, and will return all messages starting from that time
`maxPageSize` will limit the number of messages per page in the `PagedCollection<ChatMessage>`

**Comment by sangkuOH** [comment]
Thanks comment!
But, i want to paging to past from present is it possible?
And, we want use this just for ChatApp,
But all SDK seem to for mixed service like zoom
It could be possible use this for chat app?

**Comment by sangkuOH** [comment]
What if I want to retrieve messages in chunks. Is this scenario even possible?
For ex: 
1. The server has 100 messages and started a week ago
2. I want to retrieve 20 per request and the retrieving next 20 messages will triggered by scrolling up.

On above scenario, how should I query the second 20 messages and so on with ListChatMessagesOptions? since the startTime in ListChatMessagesOptions confirmed as the start time of the thread, not the retrieval time.

Thanks in advance.

**Comment by kevalvadoliya** [comment]
Hello @knvsl @juancamilor, Any update on this? 
As per [service limits page](https://docs.microsoft.com/en-gb/azure/communication-services/concepts/service-limits), I can retrieve max 250 messages, What if there are more than maxPageSize messages. How can i retrieve those?

**Comment by angellan-msft** [comment]
Hello @kevalvadoliya ,

Sorry for the late reply. @knvsl is not with the team anymore. I would like to help you on this.
I noticed that you mentioned several issues above from last year. 

In order to better understand your current needs and better assist you, could you please list all the questions that you have in this chat thread again? Please introduce the context/background for each question and attach the code snippets if possible.

Regards,
Angel Lan
_Microsoft|Azure Communication Service Chat Team_

**Comment by angellan-msft** [comment]
And FYI - for the max page size, it should be "200" instead of "250" based on the doc you provided.
<img width="918" alt="image" src="https://user-images.githubusercontent.com/95160885/171943517-c6dad0ed-1386-46c4-b865-536255dc38b7.png">

**Comment by kevalvadoliya** [comment]
Hello @angellan-msft, Thanks for the clarification and the quick reply.
I am adding a chat feature to one of my existing apps, but I am not clear how pagination works for the message list. 
For some users, there are thousands of messages that I want to retrieve in chunks on a scroll up event.
Let me know if you need more details.
Thanks!

**Comment by angellan-msft** [comment]
Hello @kevalvadoliya,

Chat SDK provides a param called "ListChatMessagesOptions" for you to customize. 
You are able to customize the fields such as "maxPageSize" and "startTime".
**"maxPageSize"** is the maximum number of messages to be returned per page. The limit should be 200, which is documented in - https://docs.microsoft.com/azure/communication-services/concepts/service-limits.
**"startTime"** is the earliest point in time to get messages up to. The timestamp should be in RFC3339 format: `yyyy-MM-ddTHH:mm:ssZ`.

Below please see the sample code for pagination logic. Hope it helps.

```
let listChatMessgesOptions = ListChatMessagesOptions(maxPageSize: 200)

user.listMessages(withOptions: listChatMessgesOptions) { result, _ in
                        switch result {
                        case let .success(result):
                            //retrieve the first 200 messages
                            print("Second page:")
                            guard let messages = result.pageItems else {
                                print("No messages returned")
                                return
                            }
                            
                            for message in messages {
                                print("Received message with id: \(message.id)")
                            }
                            
                            print("Second page:")
                            result.nextPage {
                                result2 in
                                switch result2 {
                                case let .success(result2):
                                    //retrieve the next 200 messages
                                    for message in result2 {
                                        print("Received message with id: \(message.id)")
                                    }
                                case .failure:
                                        print("Failed to receive messages")
                                }
                            }                            
                        case .failure:
                                print("Failed to receive messages")
                        }
                    }
```

**Comment by angellan-msft** [comment]
If you have any other questions other than "the pagination logic", please create a new GitHub issue. Thanks!

**Comment by kevalvadoliya** [comment]
Thanks for the detailed explanation, @angellan-msft. 
I have implemented same way but didn't release, We can call `nextPage` multiple times. 
Now, i can resolve my issue. Thanks!
