### ISSUE TITLE
[BUG]: ChatClient.listThreads does not give the last message information.

### ISSUE THREAD

**Issue by sangkuOH** [Azure/azure-sdk-for-ios#959]
Hi, Now we Implementing chat through ACS.

onAppear Chat Thread list view, i can get Thread list by using ChatClient.listThreads but it don't give us participants list and last message in a thread.
for now I can get participants list by using ChatThreadClient.listParticipants. but, mast message in Thread? no way to get it.
is there any way to get last message in a thread? in step Chat Thread list view?

**Comment by tjprescott** [comment]
@knvsl @Leoaqr for comment.

**Comment by knvsl** [comment]
Hi, there isn't an API specifically for getting the last message in a thread, when you list messages they will be ordered newest to oldest. You can also use sequence id for ensuring correct order of messages
