### ISSUE TITLE
[BUG]: How can i get ThreadList sorted by lastMessageReceived

### ISSUE THREAD

**Issue by sangkuOH** [Azure/azure-sdk-for-ios#964]
Hi,
as normal Chat App, we want get ThreadList sorted by lastMessageReceived
now it seem to give us not sorted,
I try to sorting this on client, but if first page don't have lastMessageReceived thread, client can't sort it.
because client don't have correct data
is there any way to get get ThreadList sorted by lastMessageReceived?

**Comment by tjprescott** [comment]
@knvsl @Leoaqr for comment

**Comment by knvsl** [comment]
Hi, sounds like you just need to retrieve the next page of results? If you have all the threads you can sort them by lastMessageReceivedOn
