### ISSUE TITLE
[BUG] CI skips running RecordableXCTestCases

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-ios#974]
CI does not run ChatClientDVRTests. Instead it skips them.

**Comment by tjprescott** [comment]
Apparently this was just recently fixed in XCode 12.5

> XCTest now automatically includes specialized subclasses of Swift generic test classes when running tests on macOS 11.3, iOS 14.5, tvOS 14.5, watchOS 7.4, or later OS versions. This allows you to use generics to improve reusability of test classes. (23493200)

However, `xcpretty` does not process the text correctly to include failure info, but it does work. The CI should be updated to use XCode 12.5.

**Comment by tjprescott** [comment]
We need build agents that run macOS 11.3 and have XCode 12.5. Apparently there is some licensing issue with Apple regarding macOS 11 that is impeding this:
https://github.com/actions/virtual-environments/issues/2072#issuecomment-888037580

This issue is open for tracking. Once the build pipeline is updated, this will be resolved.

**Comment by benbp** [comment]
Build agents fixed by https://github.com/Azure/azure-sdk-for-ios/pull/1073 but waiting on @tjprescott for related CI fixes. Assigning to you.
